In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12,8)

# Data Cleaning for United States Metropolitian Population Growth from 2010-2020
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [10]:
population_growth_2018_2024 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/population-2018-2024.csv")

In [11]:
population_growth_2018_2024.head()

,State_Name,2018,2019,2020,2021,2022,2023,2024
0,.Alabama,4891628,4907965,5032962,5050058,5076868,5117850,5163055
1,.Alaska,736624,733603,732906,734590,733659,734654,736537
2,.Arizona,7164228,7291843,7186647,7274022,7370065,7452073,7556424
3,.Arkansas,3012161,3020985,3014399,3027127,3047429,3069856,3096080
4,.California,39437463,39437610,39527808,39152927,39125347,39181667,39364774

In [344]:
population_growth_2018_2024['State_Name'] = population_growth_2018_2024['State_Name'].str.strip('.')

In [345]:
population_growth_2018_2024.head()

,State_Name,2018,2019,2020,2021,2022,2023,2024
0,Alabama,4891628,4907965,5032962,5050058,5076868,5117850,5163055
1,Alaska,736624,733603,732906,734590,733659,734654,736537
2,Arizona,7164228,7291843,7186647,7274022,7370065,7452073,7556424
3,Arkansas,3012161,3020985,3014399,3027127,3047429,3069856,3096080
4,California,39437463,39437610,39527808,39152927,39125347,39181667,39364774

In [346]:
population_growth_2018_2024 = pd.melt(population_growth_2018_2024,
                                      id_vars = 'State_Name',
                                      var_name = 'Year',
                                      value_name = 'Population_Estimate')
population_growth_2018_2024

        State_Name  Year  Population_Estimate
0          Alabama  2018              4891628
1           Alaska  2018               736624
2          Arizona  2018              7164228
3         Arkansas  2018              3012161
4       California  2018             39437463
..             ...   ...                  ...
352       Virginia  2024              8819642
353     Washington  2024              7927958
354  West Virginia  2024              1767402
355      Wisconsin  2024              5957168
356        Wyoming  2024               586722

[357 rows x 3 columns]

In [347]:
population_growth_2018_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State_Name           357 non-null    str
 1   Year                 357 non-null    str
 2   Population_Estimate  357 non-null    int64
dtypes: int64(1), str(2)
memory usage: 8.5 KB

In [348]:
# removing District of columbia because it is not a state
population_growth_2018_2024 = population_growth_2018_2024[population_growth_2018_2024['State_Name'] != 'District of Columbia']
population_growth_2018_2024

        State_Name  Year  Population_Estimate
0          Alabama  2018              4891628
1           Alaska  2018               736624
2          Arizona  2018              7164228
3         Arkansas  2018              3012161
4       California  2018             39437463
..             ...   ...                  ...
352       Virginia  2024              8819642
353     Washington  2024              7927958
354  West Virginia  2024              1767402
355      Wisconsin  2024              5957168
356        Wyoming  2024               586722

[350 rows x 3 columns]

In [349]:
# change datatypes
population_growth_2018_2024 = population_growth_2018_2024.astype({'State_Name':'category',
                                                                  'Year':'int16'})

----------------------------------------------------------------------------------------------------------------------------------

# Data Quality Check: Python vs Excel (2018-2024)
### Description 
- check for duplicates and data inconsistency

In [350]:
population_growth_2018_2024.duplicated().sum()

np.int64(0)

In [351]:
population_growth_2018_2024['State_Name'].nunique()

50

In [352]:
# save population_growth_2018_2024 as pop_growth_2018_2024.csv
population_growth_2018_2024.to_csv('pop_growth_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States CPI_data from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [12]:
cpi_data = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/cpi_data.csv")
cpi_data

    observation_date  CPIAUCSL
0         2015-01-01   234.747
1         2015-02-01   235.342
2         2015-03-01   235.976
3         2015-04-01   236.222
4         2015-05-01   237.001
..               ...       ...
115       2024-08-01   314.131
116       2024-09-01   314.851
117       2024-10-01   315.564
118       2024-11-01   316.449
119       2024-12-01   317.603

[120 rows x 2 columns]

In [13]:
# Rename columns
cpi_data.columns = ['Date', 'Average_CPI']

# Convert to datetime
cpi_data['Date'] = pd.to_datetime(cpi_data['Date'])

In [14]:
cpi_data = cpi_data[cpi_data['Date'] >= '2018-01-01']
cpi_data

          Date  Average_CPI
36  2018-01-01      248.859
37  2018-02-01      249.529
38  2018-03-01      249.577
39  2018-04-01      250.227
40  2018-05-01      250.792
..         ...          ...
115 2024-08-01      314.131
116 2024-09-01      314.851
117 2024-10-01      315.564
118 2024-11-01      316.449
119 2024-12-01      317.603

[84 rows x 2 columns]

In [356]:
# Set 2018-01-01 as base month
base_month = '2018-01-01'
base_cpi = cpi_data[cpi_data['Date'] == base_month]['Average_CPI'].values[0]

# Calculate CPI Index
cpi_data.loc[:, 'CPI_Index'] = (cpi_data.loc[:,'Average_CPI'] / base_cpi) * 100

# Keep relevant columns
monthly_cpi = cpi_data[['Date', 'Average_CPI', 'CPI_Index']]

monthly_cpi

          Date  Average_CPI   CPI_Index
36  2018-01-01      248.859  100.000000
37  2018-02-01      249.529  100.269229
38  2018-03-01      249.577  100.288517
39  2018-04-01      250.227  100.549709
40  2018-05-01      250.792  100.776745
..         ...          ...         ...
115 2024-08-01      314.131  126.228507
116 2024-09-01      314.851  126.517827
117 2024-10-01      315.564  126.804335
118 2024-11-01      316.449  127.159958
119 2024-12-01      317.603  127.623674

[84 rows x 3 columns]

In [357]:
monthly_cpi = monthly_cpi.reset_index(drop=True)
monthly_cpi.head()

        Date  Average_CPI   CPI_Index
0 2018-01-01      248.859  100.000000
1 2018-02-01      249.529  100.269229
2 2018-03-01      249.577  100.288517
3 2018-04-01      250.227  100.549709
4 2018-05-01      250.792  100.776745

In [358]:
monthly_cpi = monthly_cpi.copy()
monthly_cpi.loc[:, 'Year'] = monthly_cpi['Date'].astype(str).str[:4].astype(int)

In [359]:
cpi_2018_2024 = monthly_cpi

In [360]:
cpi_2018_2024 = cpi_2018_2024[['Year', 'Average_CPI', 'CPI_Index']]
cpi_2018_2024

    Year  Average_CPI   CPI_Index
0   2018      248.859  100.000000
1   2018      249.529  100.269229
2   2018      249.577  100.288517
3   2018      250.227  100.549709
4   2018      250.792  100.776745
..   ...          ...         ...
79  2024      314.131  126.228507
80  2024      314.851  126.517827
81  2024      315.564  126.804335
82  2024      316.449  127.159958
83  2024      317.603  127.623674

[84 rows x 3 columns]

In [361]:
cpi_df = cpi_2018_2024.groupby('Year').agg({'Average_CPI': 'mean'}).reset_index()
cpi_df

   Year  Average_CPI
0  2018   251.099500
1  2019   255.652583
2  2020   258.855750
3  2021   270.967917
4  2022   292.625417
5  2023   304.704167
6  2024   313.697833

In [362]:
# Set 2018 as base year
base_year = 2018
base_cpi = cpi_df[cpi_df['Year'] == base_year]['Average_CPI'].values[0]

# Calculate CPI Index
cpi_df.loc[:, 'CPI_Index'] = (cpi_df['Average_CPI'] / base_cpi) * 100

# Keep relevant columns
yearly_cpi = cpi_df[['Year', 'Average_CPI', 'CPI_Index']]

yearly_cpi

   Year  Average_CPI   CPI_Index
0  2018   251.099500  100.000000
1  2019   255.652583  101.813259
2  2020   258.855750  103.088915
3  2021   270.967917  107.912567
4  2022   292.625417  116.537634
5  2023   304.704167  121.347978
6  2024   313.697833  124.929693

In [363]:
# save monthly_cpi as cpi_2018_2024.csv
yearly_cpi.to_csv('cpi_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States Mortgage_rates_data from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [15]:
mortgage_rates_2015_2024 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/mortgage-rates.csv")
mortgage_rates_2015_2024

    observation_date  MORTGAGE30US
0         2015-01-08          3.73
1         2015-01-15          3.66
2         2015-01-22          3.63
3         2015-01-29          3.66
4         2015-02-05          3.59
..               ...           ...
516       2024-11-27          6.81
517       2024-12-05          6.69
518       2024-12-12          6.60
519       2024-12-19          6.72
520       2024-12-26          6.85

[521 rows x 2 columns]

In [365]:
# Rename columns
mortgage_rates_2015_2024.columns = ['Date', 'Mortgage_Rate_pct']

# Convert to datetime
mortgage_rates_2015_2024['Date'] = pd.to_datetime(mortgage_rates_2015_2024['Date'])

# Resample to monthly average
mortgage_monthly_2015_2024 = mortgage_rates_2015_2024.resample('ME', on='Date').mean().reset_index()

mortgage_monthly_2015_2024

          Date  Mortgage_Rate_pct
0   2015-01-31              3.670
1   2015-02-28              3.710
2   2015-03-31              3.770
3   2015-04-30              3.672
4   2015-05-31              3.840
..         ...                ...
115 2024-08-31              6.500
116 2024-09-30              6.180
117 2024-10-31              6.428
118 2024-11-30              6.805
119 2024-12-31              6.715

[120 rows x 2 columns]

In [366]:
mortgage_monthly_2018_2024 = mortgage_monthly_2015_2024[mortgage_monthly_2015_2024['Date'] >= '2018-01-01']
mortgage_monthly_2018_2024

          Date  Mortgage_Rate_pct
36  2018-01-31             4.0325
37  2018-02-28             4.3300
38  2018-03-31             4.4440
39  2018-04-30             4.4675
40  2018-05-31             4.5860
..         ...                ...
115 2024-08-31             6.5000
116 2024-09-30             6.1800
117 2024-10-31             6.4280
118 2024-11-30             6.8050
119 2024-12-31             6.7150

[84 rows x 2 columns]

In [367]:
mortgage_monthly_2018_2024 = mortgage_monthly_2018_2024.reset_index(drop=True)
mortgage_monthly_2018_2024.head()

        Date  Mortgage_Rate_pct
0 2018-01-31             4.0325
1 2018-02-28             4.3300
2 2018-03-31             4.4440
3 2018-04-30             4.4675
4 2018-05-31             4.5860

In [368]:
mortgage_monthly_2018_2024['Year'] = pd.to_datetime(
    mortgage_monthly_2018_2024['Date']
).dt.year

In [369]:
mortgage_yearly = (
    mortgage_monthly_2018_2024
    .groupby('Year')['Mortgage_Rate_pct']
    .mean()
    .reset_index()
)

In [370]:
mortgage_yearly

   Year  Mortgage_Rate_pct
0  2018           4.539042
1  2019           3.933750
2  2020           3.113667
3  2021           2.955708
4  2022           5.327500
5  2023           6.795375
6  2024           6.723667

In [371]:
# save mortgage_yearly as mortgage_2018_2024
mortgage_yearly.to_csv('mortgage_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States census-income data from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [16]:
census_income_2018_2024 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/census_income.csv")
census_income_2018_2024

,observation_date,MEHOINUSA672N,MEHOINUSAKA672N,MEHOINUSALA672N,MEHOINUSARA672N,MEHOINUSAZA672N,MEHOINUSCAA672N,MEHOINUSCOA672N,MEHOINUSCTA672N,MEHOINUSDCA672N,...,MEHOINUSSDA672N,MEHOINUSTNA672N,MEHOINUSTXA672N,MEHOINUSUTA672N,MEHOINUSVAA672N,MEHOINUSVTA672N,MEHOINUSWAA672N,MEHOINUSWIA672N,MEHOINUSWVA672N,MEHOINUSWYA672N
0,2018-01-01,77700,84540,61420,61230,76600,86690,89820,89550,105500,...,73130,68950,73530,94780,94890,86170,98060,77030,62200,76920
1,2019-01-01,83260,95010,68110,66100,85650,94660,87870,105800,112800,...,77870,68630,81740,102400,98550,90050,99930,81630,65090,78940
2,2020-01-01,81580,89650,65600,60900,80470,93140,100500,95280,105800,...,84190,65940,82050,100700,98610,80670,97580,80850,62340,78500
3,2021-01-01,81270,93150,65360,58310,81310,93660,97540,92950,104100,...,84840,71370,77390,100600,92160,87350,100600,80300,53770,81580
4,2022-01-01,79500,95670,63870,57540,78300,90930,95870,96720,108400,...,71620,69700,79560,102100,90790,76960,95330,78170,55920,77920
5,2023-01-01,82690,100700,62230,64880,84800,92200,99140,94620,113900,...,83860,74580,81110,103800,98990,87400,95850,81750,61970,79200
6,2024-01-01,83730,91260,65560,64840,84700,100600,106500,99240,104800,...,79850,75860,81490,104000,97720,85260,97500,82560,63150,78680

In [373]:
income_long = census_income_2018_2024.melt(
    id_vars='observation_date',
    var_name='Series_Code',
    value_name='Median_Income'
)
income_long

    observation_date      Series_Code  Median_Income
0         2018-01-01    MEHOINUSA672N          77700
1         2019-01-01    MEHOINUSA672N          83260
2         2020-01-01    MEHOINUSA672N          81580
3         2021-01-01    MEHOINUSA672N          81270
4         2022-01-01    MEHOINUSA672N          79500
..               ...              ...            ...
359       2020-01-01  MEHOINUSWYA672N          78500
360       2021-01-01  MEHOINUSWYA672N          81580
361       2022-01-01  MEHOINUSWYA672N          77920
362       2023-01-01  MEHOINUSWYA672N          79200
363       2024-01-01  MEHOINUSWYA672N          78680

[364 rows x 3 columns]

In [374]:
# extracts the Abbreviation
income_long['State_Abbr'] = (
    income_long['Series_Code']
    .str[8:10]   # extracts the two-letter state code
)
income_long

    observation_date      Series_Code  Median_Income State_Abbr
0         2018-01-01    MEHOINUSA672N          77700         A6
1         2019-01-01    MEHOINUSA672N          83260         A6
2         2020-01-01    MEHOINUSA672N          81580         A6
3         2021-01-01    MEHOINUSA672N          81270         A6
4         2022-01-01    MEHOINUSA672N          79500         A6
..               ...              ...            ...        ...
359       2020-01-01  MEHOINUSWYA672N          78500         WY
360       2021-01-01  MEHOINUSWYA672N          81580         WY
361       2022-01-01  MEHOINUSWYA672N          77920         WY
362       2023-01-01  MEHOINUSWYA672N          79200         WY
363       2024-01-01  MEHOINUSWYA672N          78680         WY

[364 rows x 4 columns]

In [375]:
income_long = income_long.rename(columns={'observation_date': 'Date'})
income_long

           Date      Series_Code  Median_Income State_Abbr
0    2018-01-01    MEHOINUSA672N          77700         A6
1    2019-01-01    MEHOINUSA672N          83260         A6
2    2020-01-01    MEHOINUSA672N          81580         A6
3    2021-01-01    MEHOINUSA672N          81270         A6
4    2022-01-01    MEHOINUSA672N          79500         A6
..          ...              ...            ...        ...
359  2020-01-01  MEHOINUSWYA672N          78500         WY
360  2021-01-01  MEHOINUSWYA672N          81580         WY
361  2022-01-01  MEHOINUSWYA672N          77920         WY
362  2023-01-01  MEHOINUSWYA672N          79200         WY
363  2024-01-01  MEHOINUSWYA672N          78680         WY

[364 rows x 4 columns]

In [376]:
census_income_2018_2024 = income_long[['Date', 'State_Abbr', 'Median_Income']]
census_income_2018_2024

           Date State_Abbr  Median_Income
0    2018-01-01         A6          77700
1    2019-01-01         A6          83260
2    2020-01-01         A6          81580
3    2021-01-01         A6          81270
4    2022-01-01         A6          79500
..          ...        ...            ...
359  2020-01-01         WY          78500
360  2021-01-01         WY          81580
361  2022-01-01         WY          77920
362  2023-01-01         WY          79200
363  2024-01-01         WY          78680

[364 rows x 3 columns]

In [377]:
# selected only states.. dropped usa
census_income_2018_2024 = census_income_2018_2024[~census_income_2018_2024['State_Abbr'].str.contains('A6')]
census_income_2018_2024

           Date State_Abbr  Median_Income
7    2018-01-01         AK          84540
8    2019-01-01         AK          95010
9    2020-01-01         AK          89650
10   2021-01-01         AK          93150
11   2022-01-01         AK          95670
..          ...        ...            ...
359  2020-01-01         WY          78500
360  2021-01-01         WY          81580
361  2022-01-01         WY          77920
362  2023-01-01         WY          79200
363  2024-01-01         WY          78680

[357 rows x 3 columns]

In [378]:
census_income_2018_2024.columns

Index(['Date', 'State_Abbr', 'Median_Income'], dtype='str')

In [379]:
census_income_2018_2024 = census_income_2018_2024.copy()
census_income_2018_2024.loc[:, 'Year'] = census_income_2018_2024.loc[:, 'Date'].astype(str).str[:4].astype(int)

In [380]:
census_income_2018_2024 = census_income_2018_2024[['Year', 'State_Abbr', 'Median_Income']]

In [381]:
census_income_2018_2024 = census_income_2018_2024.groupby(['State_Abbr', 'Year']).agg({'Median_Income': 'median'}).reset_index()

In [382]:
census_income_2018_2024

    State_Abbr  Year  Median_Income
0           AK  2018        84540.0
1           AK  2019        95010.0
2           AK  2020        89650.0
3           AK  2021        93150.0
4           AK  2022        95670.0
..         ...   ...            ...
352         WY  2020        78500.0
353         WY  2021        81580.0
354         WY  2022        77920.0
355         WY  2023        79200.0
356         WY  2024        78680.0

[357 rows x 3 columns]

In [383]:
# remove District of columbia(DC)
census_income_2018_2024 = census_income_2018_2024[census_income_2018_2024['State_Abbr'] != 'DC']

In [384]:
census_income_2018_2024

    State_Abbr  Year  Median_Income
0           AK  2018        84540.0
1           AK  2019        95010.0
2           AK  2020        89650.0
3           AK  2021        93150.0
4           AK  2022        95670.0
..         ...   ...            ...
352         WY  2020        78500.0
353         WY  2021        81580.0
354         WY  2022        77920.0
355         WY  2023        79200.0
356         WY  2024        78680.0

[350 rows x 3 columns]

In [385]:
# census_income_2018_2024 as census_income_2018_2024.csv
census_income_2018_2024.to_csv('census_income_2018_2024.csv', index=False)

# Data Cleaning for United States house estimate data from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [386]:
import requests

years = {
    2018:"acs1",
    2019:"acs1",
    2020:"acs5",
    2021:"acs1",
    2022:"acs1",
    2023:"acs1",
    2024:"acs1"
}

all_data = []

for year, dataset in years.items():
    url = f"https://api.census.gov/data/{year}/acs/{dataset}?get=NAME,B11001_001E&for=state:*"
    r = requests.get(url).json()

    df = pd.DataFrame(r[1:], columns=r[0])
    df["Year"] = year
    all_data.append(df)

household_estimate = pd.concat(all_data)
household_estimate.head(3)

          NAME B11001_001E state  Year
0    Wisconsin     2371960    55  2018
1      Wyoming      230252    56  2018
2  Puerto Rico     1179637    72  2018

In [387]:
household_estimate = household_estimate[~household_estimate['NAME'].isin(['District of Columbia', 'Puerto Rico'])]

In [388]:
household_estimate[household_estimate['NAME'].isin(['District of Columbia', 'Puerto Rico'])]

Empty DataFrame
Columns: [NAME, B11001_001E, state, Year]
Index: []

In [389]:
household_estimate = household_estimate.rename(columns= {'NAME': 'State_Name', 
                           'B11001_001E': 'Household_Estimate'})
household_estimate.head(3)

    State_Name Household_Estimate state  Year
0    Wisconsin            2371960    55  2018
1      Wyoming             230252    56  2018
3  Mississippi            1108630    28  2018

In [390]:
household_estimate = household_estimate.drop('state', axis=1)
household_estimate.head(3)

    State_Name Household_Estimate  Year
0    Wisconsin            2371960  2018
1      Wyoming             230252  2018
3  Mississippi            1108630  2018

In [391]:
# household_estimate as household_estimate_2018_2024
household_estimate.to_csv('household_estimate_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States Zillow Inventory data from 2018-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [17]:
zillow_inventory_2018_2025 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/zillow-inventory.csv")
zillow_inventory_2018_2025

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
0,102001,0,United States,country,NaN,1421529.0,1500195.0,1592417.0,1660618.0,1709146.0,...,1097475.0,1167197.0,1262386.0,1329558.0,1373264.0,1380205.0,1373116.0,1362806.0,1322703.0,1238316.0
1,394913,1,"New York, NY",msa,NY,73707.0,80345.0,85864.0,90067.0,91881.0,...,37433.0,40634.0,44829.0,47708.0,49038.0,48097.0,47265.0,46782.0,45632.0,41905.0
2,753899,2,"Los Angeles, CA",msa,CA,21998.0,23784.0,25605.0,27109.0,28811.0,...,19912.0,21628.0,23659.0,25128.0,26379.0,26688.0,26539.0,25801.0,24240.0,21820.0
3,394463,3,"Chicago, IL",msa,IL,38581.0,42253.0,45757.0,47492.0,48984.0,...,18896.0,20089.0,21804.0,23133.0,24026.0,24129.0,24076.0,23989.0,22985.0,20614.0
4,394514,4,"Dallas, TX",msa,TX,24042.0,25876.0,28224.0,30490.0,32408.0,...,29656.0,31942.0,35041.0,37501.0,38954.0,39091.0,38265.0,37323.0,35777.0,33427.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,55.0,55.0,56.0,66.0,65.0,...,38.0,40.0,42.0,43.0,45.0,44.0,44.0,42.0,43.0,45.0
924,394743,936,"Ketchikan, AK",msa,AK,77.0,78.0,80.0,92.0,104.0,...,50.0,55.0,59.0,62.0,63.0,67.0,67.0,65.0,60.0,54.0
925,753874,937,"Craig, CO",msa,CO,115.0,116.0,126.0,148.0,165.0,...,53.0,57.0,70.0,82.0,92.0,92.0,92.0,88.0,82.0,69.0
926,395188,938,"Vernon, TX",msa,TX,21.0,26.0,32.0,39.0,39.0,...,47.0,50.0,51.0,51.0,56.0,62.0,64.0,63.0,57.0,52.0
927,394767,939,"Lamesa, TX",msa,TX,35.0,35.0,37.0,38.0,41.0,...,29.0,27.0,29.0,31.0,34.0,32.0,32.0,33.0,35.0,35.0

In [393]:
zillow_inventory_2018_2025.dtypes

RegionID        int64
SizeRank        int64
RegionName        str
RegionType        str
StateName         str
               ...
2025-08-31    float64
2025-09-30    float64
2025-10-31    float64
2025-11-30    float64
2025-12-31    float64
Length: 99, dtype: object

In [394]:
zillow_inventory_2018_2025.describe()

,RegionID,SizeRank,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
count,928.000000,928.000000,8.990000e+02,8.990000e+02,8.990000e+02,9.000000e+02,9.000000e+02,9.000000e+02,9.000000e+02,9.000000e+02,...,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02,9.280000e+02
mean,425513.622845,469.393319,3.023945e+03,3.193825e+03,3.390195e+03,3.527522e+03,3.626633e+03,3.675371e+03,3.654210e+03,3.610303e+03,...,2.284196e+03,2.430290e+03,2.627736e+03,2.765407e+03,2.853364e+03,2.864516e+03,2.847635e+03,2.825946e+03,2.743198e+03,2.567765e+03
std,105810.435670,271.133088,4.756083e+04,5.019643e+04,5.328036e+04,5.552719e+04,5.714447e+04,5.794935e+04,5.760422e+04,5.688007e+04,...,3.616243e+04,3.845848e+04,4.158891e+04,4.379593e+04,4.522945e+04,4.545224e+04,4.521442e+04,4.487284e+04,4.355332e+04,4.077752e+04
min,102001.000000,0.000000,1.200000e+01,1.100000e+01,1.300000e+01,6.000000e+00,7.000000e+00,8.000000e+00,7.000000e+00,8.000000e+00,...,2.900000e+01,2.700000e+01,2.900000e+01,3.100000e+01,3.200000e+01,3.100000e+01,3.100000e+01,3.200000e+01,3.200000e+01,3.100000e+01
25%,394555.750000,234.750000,1.950000e+02,2.025000e+02,2.125000e+02,2.260000e+02,2.307500e+02,2.385000e+02,2.370000e+02,2.357500e+02,...,1.197500e+02,1.250000e+02,1.330000e+02,1.397500e+02,1.490000e+02,1.527500e+02,1.550000e+02,1.560000e+02,1.510000e+02,1.430000e+02
50%,394812.500000,470.500000,4.000000e+02,4.070000e+02,4.350000e+02,4.650000e+02,4.855000e+02,5.000000e+02,5.075000e+02,4.995000e+02,...,2.440000e+02,2.560000e+02,2.810000e+02,2.980000e+02,3.120000e+02,3.195000e+02,3.245000e+02,3.250000e+02,3.115000e+02,2.950000e+02
75%,395073.500000,703.250000,1.013500e+03,1.077000e+03,1.130000e+03,1.163000e+03,1.207250e+03,1.234500e+03,1.222500e+03,1.197000e+03,...,6.120000e+02,6.605000e+02,7.430000e+02,8.135000e+02,8.585000e+02,8.695000e+02,8.487500e+02,8.280000e+02,7.960000e+02,7.462500e+02
max,845172.000000,939.000000,1.421529e+06,1.500195e+06,1.592417e+06,1.660618e+06,1.709146e+06,1.733393e+06,1.723102e+06,1.701375e+06,...,1.097475e+06,1.167197e+06,1.262386e+06,1.329558e+06,1.373264e+06,1.380205e+06,1.373116e+06,1.362806e+06,1.322703e+06,1.238316e+06

In [395]:
zillow_inventory_2018_2025.shape

(928, 99)

In [396]:
zillow_inventory_2018_2025.duplicated().sum()

np.int64(0)

In [397]:
zillow_inventory_2018_2025.isna().sum()

RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2025-08-31    0
2025-09-30    0
2025-10-31    0
2025-11-30    0
2025-12-31    0
Length: 99, dtype: int64

In [398]:
zillow_inventory_2018_2025[zillow_inventory_2018_2025['2018-03-31'].isna()]

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
85,845159,86,"Poughkeepsie, NY",msa,NY,NaN,NaN,NaN,NaN,NaN,...,1610.0,1691.0,1897.0,2095.0,2233.0,2242.0,2221.0,2209.0,2142.0,1977.0
476,786258,483,"Fort Payne, AL",msa,AL,NaN,NaN,NaN,NaN,NaN,...,221.0,224.0,233.0,241.0,245.0,241.0,241.0,242.0,238.0,227.0
500,845163,508,"Jasper, AL",msa,AL,NaN,NaN,NaN,NaN,NaN,...,235.0,237.0,229.0,213.0,209.0,208.0,214.0,213.0,213.0,209.0
527,845162,535,"Granbury, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,668.0,720.0,799.0,847.0,867.0,850.0,814.0,780.0,738.0,697.0
587,786250,595,"Alexander City, AL",msa,AL,NaN,NaN,NaN,NaN,NaN,...,257.0,281.0,298.0,312.0,322.0,328.0,327.0,318.0,311.0,297.0
647,786259,655,"Grand Rapids, MN",msa,MN,NaN,NaN,NaN,NaN,NaN,...,106.0,125.0,166.0,204.0,232.0,235.0,232.0,223.0,212.0,188.0
724,845165,732,"Minden, LA",msa,LA,NaN,NaN,NaN,NaN,NaN,...,89.0,91.0,97.0,105.0,113.0,113.0,112.0,106.0,103.0,100.0
729,394603,737,"Fort Dodge, IA",msa,IA,NaN,NaN,NaN,NaN,NaN,...,136.0,144.0,152.0,159.0,159.0,162.0,160.0,156.0,150.0,140.0
733,786251,741,"Atmore, AL",msa,AL,NaN,NaN,NaN,NaN,NaN,...,113.0,110.0,109.0,111.0,118.0,123.0,126.0,125.0,125.0,120.0
753,786252,761,"Bonham, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,262.0,280.0,299.0,312.0,328.0,339.0,346.0,349.0,342.0,327.0
777,786262,786,"Pella, IA",msa,IA,NaN,NaN,NaN,NaN,NaN,...,94.0,101.0,113.0,119.0,119.0,125.0,128.0,127.0,120.0,110.0
792,786261,801,"Jennings, LA",msa,LA,NaN,NaN,NaN,NaN,NaN,...,103.0,104.0,109.0,114.0,115.0,114.0,117.0,120.0,118.0,110.0
797,394473,806,"Cleveland, MS",msa,MS,NaN,NaN,NaN,NaN,NaN,...,83.0,83.0,84.0,81.0,79.0,80.0,84.0,88.0,90.0,86.0
803,786264,812,"St. Marys, PA",msa,PA,NaN,NaN,NaN,NaN,NaN,...,60.0,57.0,59.0,62.0,71.0,77.0,83.0,83.0,82.0,77.0
804,786255,813,"Central City, KY",msa,KY,NaN,NaN,NaN,NaN,NaN,...,86.0,96.0,105.0,110.0,114.0,114.0,111.0,110.0,109.0,101.0
820,786260,829,"Hope, AR",msa,AR,NaN,NaN,NaN,NaN,NaN,...,83.0,82.0,84.0,89.0,91.0,94.0,94.0,99.0,101.0,100.0
828,845161,837,"Bluffton, IN",msa,IN,NaN,NaN,NaN,NaN,NaN,...,52.0,52.0,55.0,60.0,65.0,66.0,64.0,59.0,62.0,59.0
833,786256,842,"Eufaula, AL",msa,AL,NaN,NaN,NaN,NaN,NaN,...,114.0,118.0,125.0,133.0,145.0,155.0,159.0,155.0,146.0,137.0
835,845171,844,"Union, SC",msa,SC,NaN,NaN,NaN,NaN,NaN,...,66.0,69.0,70.0,68.0,68.0,67.0,69.0,68.0,69.0,69.0
842,394706,851,"Indianola, MS",msa,MS,NaN,NaN,NaN,6.0,7.0,...,39.0,41.0,41.0,43.0,44.0,45.0,47.0,49.0,53.0,55.0
863,845170,873,"Scottsburg, IN",msa,IN,NaN,NaN,NaN,NaN,NaN,...,71.0,76.0,79.0,79.0,78.0,79.0,82.0,87.0,90.0,88.0
864,845169,874,"Rockport, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,556.0,611.0,666.0,689.0,693.0,688.0,678.0,655.0,624.0,589.0
888,394659,898,"Guymon, OK",msa,OK,NaN,NaN,NaN,NaN,NaN,...,56.0,53.0,50.0,46.0,48.0,53.0,58.0,60.0,58.0,54.0
892,786254,902,"Carroll, IA",msa,IA,NaN,NaN,NaN,NaN,NaN,...,63.0,69.0,81.0,96.0,105.0,109.0,108.0,105.0,98.0,87.0
902,786263,913,"Ruidoso, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,379.0,396.0,435.0,485.0,527.0,547.0,539.0,523.0,501.0,486.0
903,786257,914,"Fairmont, MN",msa,MN,NaN,NaN,NaN,NaN,NaN,...,50.0,49.0,59.0,67.0,80.0,82.0,92.0,95.0,101.0,95.0
906,786265,917,"West Point, MS",msa,MS,NaN,NaN,NaN,NaN,NaN,...,43.0,49.0,54.0,60.0,62.0,67.0,71.0,72.0,72.0,73.0
908,845168,919,"Pearsall, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,41.0,42.0,43.0,44.0,46.0,47.0,47.0,47.0,45.0,44.0
910,786253,921,"Brownsville, TN",msa,TN,NaN,NaN,NaN,NaN,NaN,...,66.0,66.0,65.0,63.0,66.0,68.0,70.0,68.0,68.0,65.0

In [399]:
# Columns that are NOT dates (keep these fixed), change column names
id_cols = ['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName']
new_cols = ['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name']

zillow_inventory_2018_2025 = zillow_inventory_2018_2025.rename(columns=dict(zip(id_cols, new_cols)))

# Melt the dataframe
zillow_inventory_2018_2025 = zillow_inventory_2018_2025.melt(
    id_vars=new_cols,
    var_name='Date',
    value_name='Active_Listings'
)


# Convert Date column to datetime
zillow_inventory_2018_2025['Date'] = pd.to_datetime(zillow_inventory_2018_2025['Date'])

# View result
zillow_inventory_2018_2025

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Active_Listings
0,102001,0,United States,country,NaN,2018-03-31,1421529.0
1,394913,1,"New York, NY",msa,NY,2018-03-31,73707.0
2,753899,2,"Los Angeles, CA",msa,CA,2018-03-31,21998.0
3,394463,3,"Chicago, IL",msa,IL,2018-03-31,38581.0
4,394514,4,"Dallas, TX",msa,TX,2018-03-31,24042.0
...,...,...,...,...,...,...,...
87227,753929,935,"Zapata, TX",msa,TX,2025-12-31,45.0
87228,394743,936,"Ketchikan, AK",msa,AK,2025-12-31,54.0
87229,753874,937,"Craig, CO",msa,CO,2025-12-31,69.0
87230,395188,938,"Vernon, TX",msa,TX,2025-12-31,52.0
87231,394767,939,"Lamesa, TX",msa,TX,2025-12-31,35.0

In [400]:
zillow_inventory_2018_2025 = zillow_inventory_2018_2025.copy()
zillow_inventory_2018_2025.loc[:, 'Year'] = zillow_inventory_2018_2025['Date'].astype(str).str[:4].astype(int)

In [401]:
zillow_inventory_2018_2025 = zillow_inventory_2018_2025[['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name', 'Year', 'Active_Listings']]

In [402]:
zillow_inventory_2018_2025.head(2)

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Active_Listings
0,102001,0,United States,country,NaN,2018,1421529.0
1,394913,1,"New York, NY",msa,NY,2018,73707.0

In [403]:
zillow_inventory_2018_2025[zillow_inventory_2018_2025['Region_Type'].str.contains('country')]

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Active_Listings
0,102001,0,United States,country,NaN,2018,1421529.0
928,102001,0,United States,country,NaN,2018,1500195.0
1856,102001,0,United States,country,NaN,2018,1592417.0
2784,102001,0,United States,country,NaN,2018,1660618.0
3712,102001,0,United States,country,NaN,2018,1709146.0
...,...,...,...,...,...,...,...
82592,102001,0,United States,country,NaN,2025,1380205.0
83520,102001,0,United States,country,NaN,2025,1373116.0
84448,102001,0,United States,country,NaN,2025,1362806.0
85376,102001,0,United States,country,NaN,2025,1322703.0
86304,102001,0,United States,country,NaN,2025,1238316.0

In [404]:
zillow_inventory_2018_2025 = zillow_inventory_2018_2025[~zillow_inventory_2018_2025['Region_Type'].str.contains('country')]

In [405]:
zillow_inventory_2018_2025[zillow_inventory_2018_2025['Region_Type'].str.contains('country')]

Empty DataFrame
Columns: [Region_ID, Size_Rank, Region_Name, Region_Type, State_Name, Year, Active_Listings]
Index: []

In [406]:
zillow_inventory_2018_2025.head(2)

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Active_Listings
1,394913,1,"New York, NY",msa,NY,2018,73707.0
2,753899,2,"Los Angeles, CA",msa,CA,2018,21998.0

In [407]:
zillow_inventory_2018_2025[zillow_inventory_2018_2025['Year']==2025]

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Active_Listings
76097,394913,1,"New York, NY",msa,NY,2025,36838.0
76098,753899,2,"Los Angeles, CA",msa,CA,2025,18129.0
76099,394463,3,"Chicago, IL",msa,IL,2025,19217.0
76100,394514,4,"Dallas, TX",msa,TX,2025,28741.0
76101,394692,5,"Houston, TX",msa,TX,2025,27451.0
...,...,...,...,...,...,...,...
87227,753929,935,"Zapata, TX",msa,TX,2025,45.0
87228,394743,936,"Ketchikan, AK",msa,AK,2025,54.0
87229,753874,937,"Craig, CO",msa,CO,2025,69.0
87230,395188,938,"Vernon, TX",msa,TX,2025,52.0
87231,394767,939,"Lamesa, TX",msa,TX,2025,35.0

In [408]:
# remove 2025 rows
zillow_inventory_2018_2024 = zillow_inventory_2018_2025.loc[zillow_inventory_2018_2025['Year'] != 2025]

In [409]:
zillow_inventory_2018_2024[zillow_inventory_2018_2024['Year']==2025]

Empty DataFrame
Columns: [Region_ID, Size_Rank, Region_Name, Region_Type, State_Name, Year, Active_Listings]
Index: []

In [410]:
zillow_inventory_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Active_Listings
1,394913,1,"New York, NY",msa,NY,2018,73707.0
2,753899,2,"Los Angeles, CA",msa,CA,2018,21998.0
3,394463,3,"Chicago, IL",msa,IL,2018,38581.0
4,394514,4,"Dallas, TX",msa,TX,2018,24042.0
5,394692,5,"Houston, TX",msa,TX,2018,25618.0
...,...,...,...,...,...,...,...
76091,753929,935,"Zapata, TX",msa,TX,2024,39.0
76092,394743,936,"Ketchikan, AK",msa,AK,2024,46.0
76093,753874,937,"Craig, CO",msa,CO,2024,71.0
76094,395188,938,"Vernon, TX",msa,TX,2024,42.0
76095,394767,939,"Lamesa, TX",msa,TX,2024,30.0

In [411]:
zillow_inventory_2018_2024.duplicated().sum()

np.int64(5808)

In [412]:
zillow_inventory_2018_2024 = zillow_inventory_2018_2024.drop_duplicates()

In [413]:
zillow_inventory_2018_2024.duplicated().sum()

np.int64(0)

In [414]:
# Average monthly active listings per metro per year
metro_avg_inventory = zillow_inventory_2018_2024.groupby(['Region_Name','State_Name','Year'])['Active_Listings'].mean().reset_index()
metro_avg_inventory

       Region_Name State_Name  Year  Active_Listings
0     Aberdeen, SD         SD  2018       251.900000
1     Aberdeen, SD         SD  2019       221.083333
2     Aberdeen, SD         SD  2020       174.545455
3     Aberdeen, SD         SD  2021       134.727273
4     Aberdeen, SD         SD  2022       117.363636
...            ...        ...   ...              ...
6484    Zapata, TX         TX  2020        31.900000
6485    Zapata, TX         TX  2021        26.666667
6486    Zapata, TX         TX  2022        42.000000
6487    Zapata, TX         TX  2023        43.875000
6488    Zapata, TX         TX  2024        42.285714

[6489 rows x 4 columns]

In [415]:
# Sum across metros to get state totals
state_totals_inventory = metro_avg_inventory.groupby(['State_Name','Year'])['Active_Listings'].sum().reset_index()
state_totals_inventory

    State_Name  Year  Active_Listings
0           AK  2018      2969.711111
1           AK  2019      2840.244949
2           AK  2020      2329.938889
3           AK  2021      1771.522222
4           AK  2022      1433.678788
..         ...   ...              ...
345         WY  2020      2357.069697
346         WY  2021      1803.892424
347         WY  2022      1760.998485
348         WY  2023      1841.687879
349         WY  2024      1889.562121

[350 rows x 3 columns]

In [416]:
state_totals_inventory.groupby('Year')['Active_Listings'].sum()

Year
2018    1.477684e+06
2019    1.429300e+06
2020    1.160347e+06
2021    9.268609e+05
2022    8.930999e+05
2023    8.604096e+05
2024    9.879497e+05
Name: Active_Listings, dtype: float64

In [417]:
state_totals_inventory.groupby(['State_Name','Year'])['Active_Listings'].median()

State_Name  Year
AK          2018    2969.711111
            2019    2840.244949
            2020    2329.938889
            2021    1771.522222
            2022    1433.678788
                       ...
WY          2020    2357.069697
            2021    1803.892424
            2022    1760.998485
            2023    1841.687879
            2024    1889.562121
Name: Active_Listings, Length: 350, dtype: float64

In [418]:
zillow_inventory_2018_2024 = state_totals_inventory.copy()

In [419]:
zillow_inventory_2018_2024.head()

  State_Name  Year  Active_Listings
0         AK  2018      2969.711111
1         AK  2019      2840.244949
2         AK  2020      2329.938889
3         AK  2021      1771.522222
4         AK  2022      1433.678788

In [420]:
# zillow_inventory_2018_2024 as inventory_2018_2024.csv
zillow_inventory_2018_2024.to_csv('inventory_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States Zillow Rental Price data from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [18]:
zillow_rental_price_2015_2025 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/zillow-rental-price.csv")
zillow_rental_price_2015_2025

,RegionID,SizeRank,RegionName,RegionType,StateName,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
0,102001,0,United States,country,NaN,1140.794206,1147.004813,1155.560316,1164.289390,1172.963764,...,1889.933028,1900.382656,1908.023199,1913.005005,1915.126812,1915.568633,1913.972645,1910.345210,1904.737525,1900.508394
1,394913,1,"New York, NY",msa,NY,2142.533139,2156.777831,2175.216467,2193.437280,2207.721391,...,3137.526825,3166.766024,3193.929354,3224.423948,3253.238959,3273.658647,3270.725420,3257.950926,3236.985653,3225.347753
2,753899,2,"Los Angeles, CA",msa,CA,1747.125998,1758.489772,1773.611289,1788.492103,1803.158541,...,2891.408021,2892.011548,2896.330691,2900.847412,2903.392040,2904.506887,2904.006350,2901.356180,2894.495543,2885.023436
3,394463,3,"Chicago, IL",msa,IL,1326.021449,1332.973379,1342.763089,1351.681304,1361.262062,...,1993.479724,2014.922290,2033.860696,2051.443912,2062.052532,2065.855132,2064.525240,2059.447618,2054.480821,2051.787031
4,394514,4,"Dallas, TX",msa,TX,1048.581246,1053.334256,1060.787192,1071.893851,1081.137742,...,1655.918024,1667.260008,1670.571617,1671.683716,1668.289177,1664.451936,1659.646198,1653.461217,1647.264150,1642.104111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,394805,916,"Los Alamos, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2583.333333
682,394330,920,"Andrews, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1616.666667
683,786253,921,"Brownsville, TN",msa,TN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1015.841599,1041.250000
684,395104,926,"Snyder, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1175.000000
685,395186,932,"Vermillion, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.000000

In [422]:
zillow_rental_price_2015_2025.dtypes

RegionID        int64
SizeRank        int64
RegionName        str
RegionType        str
StateName         str
               ...
2025-08-31    float64
2025-09-30    float64
2025-10-31    float64
2025-11-30    float64
2025-12-31    float64
Length: 137, dtype: object

In [423]:
zillow_rental_price_2015_2025.shape

(686, 137)

In [424]:
zillow_rental_price_2015_2025.info

<bound method DataFrame.info of      RegionID  SizeRank       RegionName RegionType StateName   2015-01-31  \
0      102001         0    United States    country       NaN  1140.794206
1      394913         1     New York, NY        msa        NY  2142.533139
2      753899         2  Los Angeles, CA        msa        CA  1747.125998
3      394463         3      Chicago, IL        msa        IL  1326.021449
4      394514         4       Dallas, TX        msa        TX  1048.581246
..        ...       ...              ...        ...       ...          ...
681    394805       916   Los Alamos, NM        msa        NM          NaN
682    394330       920      Andrews, TX        msa        TX          NaN
683    786253       921  Brownsville, TN        msa        TN          NaN
684    395104       926       Snyder, TX        msa        TX          NaN
685    395186       932   Vermillion, SD        msa        SD          NaN

      2015-02-28   2015-03-31   2015-04-30   2015-05-31  ...   2025-03-31  \
0    1147.004813  1155.560316  1164.289390  1172.963764  ...  1889.933028
1    2156.777831  2175.216467  2193.437280  2207.721391  ...  3137.526825
2    1758.489772  1773.611289  1788.492103  1803.158541  ...  2891.408021
3    1332.973379  1342.763089  1351.681304  1361.262062  ...  1993.479724
4    1053.334256  1060.787192  1071.893851  1081.137742  ...  1655.918024
..           ...          ...          ...          ...  ...          ...
681          NaN          NaN          NaN          NaN  ...          NaN
682          NaN          NaN          NaN          NaN  ...          NaN
683          NaN          NaN          NaN          NaN  ...          NaN
684          NaN          NaN          NaN          NaN  ...          NaN
685          NaN          NaN          NaN          NaN  ...          NaN

      2025-04-30   2025-05-31   2025-06-30   2025-07-31   2025-08-31  \
0    1900.382656  1908.023199  1913.005005  1915.126812  1915.568633
1    3166.766024  3193.929354  3224.423948  3253.238959  3273.658647
2    2892.011548  2896.330691  2900.847412  2903.392040  2904.506887
3    2014.922290  2033.860696  2051.443912  2062.052532  2065.855132
4    1667.260008  1670.571617  1671.683716  1668.289177  1664.451936
..           ...          ...          ...          ...          ...
681          NaN          NaN          NaN          NaN          NaN
682          NaN          NaN          NaN          NaN          NaN
683          NaN          NaN          NaN          NaN          NaN
684          NaN          NaN          NaN          NaN          NaN
685          NaN          NaN          NaN          NaN          NaN

      2025-09-30   2025-10-31   2025-11-30   2025-12-31
0    1913.972645  1910.345210  1904.737525  1900.508394
1    3270.725420  3257.950926  3236.985653  3225.347753
2    2904.006350  2901.356180  2894.495543  2885.023436
3    2064.525240  2059.447618  2054.480821  2051.787031
4    1659.646198  1653.461217  1647.264150  1642.104111
..           ...          ...          ...          ...
681          NaN          NaN          NaN  2583.333333
682          NaN          NaN          NaN  1616.666667
683          NaN          NaN  1015.841599  1041.250000
684          NaN          NaN          NaN  1175.000000
685          NaN          NaN          NaN   750.000000

[686 rows x 137 columns]>

In [425]:
zillow_rental_price_2015_2025.iloc[:,:20]

,RegionID,SizeRank,RegionName,RegionType,StateName,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31
0,102001,0,United States,country,NaN,1140.794206,1147.004813,1155.560316,1164.289390,1172.963764,1180.511734,1186.076047,1189.608362,1191.455408,1191.839776,1192.188379,1192.612271,1195.585085,1200.311325,1206.231375
1,394913,1,"New York, NY",msa,NY,2142.533139,2156.777831,2175.216467,2193.437280,2207.721391,2222.239171,2232.391455,2242.077410,2246.076103,2244.189913,2235.188866,2226.108416,2223.371863,2227.669550,2236.146604
2,753899,2,"Los Angeles, CA",msa,CA,1747.125998,1758.489772,1773.611289,1788.492103,1803.158541,1814.979060,1827.372590,1837.460867,1847.242516,1851.769121,1856.352272,1862.326219,1872.330771,1883.134466,1894.175846
3,394463,3,"Chicago, IL",msa,IL,1326.021449,1332.973379,1342.763089,1351.681304,1361.262062,1370.386763,1374.686830,1377.157835,1372.307504,1365.590115,1359.481547,1360.107959,1367.651585,1376.396558,1387.163010
4,394514,4,"Dallas, TX",msa,TX,1048.581246,1053.334256,1060.787192,1071.893851,1081.137742,1089.199120,1095.558164,1098.693802,1099.941283,1099.355956,1100.174662,1101.922665,1104.014106,1109.815849,1117.714778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,394805,916,"Los Alamos, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,394330,920,"Andrews, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,786253,921,"Brownsville, TN",msa,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,395104,926,"Snyder, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,395186,932,"Vermillion, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [426]:
# Convert column names to datetime where possible

df = zillow_rental_price_2015_2025

# Convert columns to datetime where possible
date_cols = pd.to_datetime(df.columns,format='%Y-%m-%d', errors='coerce')

start_date = pd.to_datetime('2018-01-01')
end_date = pd.to_datetime('2024-12-31')

date_mask = (date_cols >= start_date) & (date_cols <= end_date)

# Select only valid date columns
selected_date_cols = df.columns[date_mask]

# ID columns (already a list)

id_cols = ['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName']
new_cols = ['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name']

df = df.rename(columns=dict(zip(id_cols, new_cols)))

# Combine them correctly
df_filtered = df[new_cols + selected_date_cols.tolist()]

In [427]:
df_filtered.head()

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,...,2024-03-31,2024-04-30,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31
0,102001,0,United States,country,NaN,1291.712087,1298.898649,1308.189871,1317.427924,1325.365963,...,1829.053370,1839.849735,1850.769760,1860.148358,1867.243541,1870.201059,1870.024104,1866.423174,1863.476020,1861.600355
1,394913,1,"New York, NY",msa,NY,2294.014898,2300.730863,2313.712699,2332.336316,2349.889148,...,3015.337811,3041.984876,3071.091954,3096.725150,3112.733576,3117.987602,3108.793887,3095.737409,3086.050890,3081.557165
2,753899,2,"Los Angeles, CA",msa,CA,2086.965744,2099.110260,2109.587060,2118.378222,2125.902416,...,2780.128586,2789.363848,2800.115687,2811.519892,2823.269750,2829.880068,2834.091013,2831.689334,2827.836555,2822.269294
3,394463,3,"Chicago, IL",msa,IL,1434.379932,1445.393959,1457.605500,1468.251349,1478.077965,...,1885.676620,1904.520661,1920.963186,1936.543063,1944.874347,1948.546094,1947.715529,1946.098536,1945.845031,1949.748155
4,394514,4,"Dallas, TX",msa,TX,1210.774226,1216.439985,1223.567612,1231.277459,1236.330788,...,1642.156617,1647.537419,1654.374809,1660.546828,1664.077060,1663.971685,1658.108910,1651.392138,1642.977176,1637.333890

In [428]:
zillow_rental_price_2018_2024 = df_filtered.melt(
    id_vars=new_cols,
    var_name='Date',
    value_name='Median_Rent_Price'
)

zillow_rental_price_2018_2024['Date'] = pd.to_datetime(zillow_rental_price_2018_2024['Date'])

In [429]:
zillow_rental_price_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Median_Rent_Price
0,102001,0,United States,country,NaN,2018-01-31,1291.712087
1,394913,1,"New York, NY",msa,NY,2018-01-31,2294.014898
2,753899,2,"Los Angeles, CA",msa,CA,2018-01-31,2086.965744
3,394463,3,"Chicago, IL",msa,IL,2018-01-31,1434.379932
4,394514,4,"Dallas, TX",msa,TX,2018-01-31,1210.774226
...,...,...,...,...,...,...,...
57619,394805,916,"Los Alamos, NM",msa,NM,2024-12-31,NaN
57620,394330,920,"Andrews, TX",msa,TX,2024-12-31,NaN
57621,786253,921,"Brownsville, TN",msa,TN,2024-12-31,NaN
57622,395104,926,"Snyder, TX",msa,TX,2024-12-31,NaN
57623,395186,932,"Vermillion, SD",msa,SD,2024-12-31,NaN

In [430]:
zillow_rental_price_2018_2024 = zillow_rental_price_2018_2024[~zillow_rental_price_2018_2024['Region_Type'].str.contains('country')]
zillow_rental_price_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Median_Rent_Price
1,394913,1,"New York, NY",msa,NY,2018-01-31,2294.014898
2,753899,2,"Los Angeles, CA",msa,CA,2018-01-31,2086.965744
3,394463,3,"Chicago, IL",msa,IL,2018-01-31,1434.379932
4,394514,4,"Dallas, TX",msa,TX,2018-01-31,1210.774226
5,394692,5,"Houston, TX",msa,TX,2018-01-31,1274.087578
...,...,...,...,...,...,...,...
57619,394805,916,"Los Alamos, NM",msa,NM,2024-12-31,NaN
57620,394330,920,"Andrews, TX",msa,TX,2024-12-31,NaN
57621,786253,921,"Brownsville, TN",msa,TN,2024-12-31,NaN
57622,395104,926,"Snyder, TX",msa,TX,2024-12-31,NaN
57623,395186,932,"Vermillion, SD",msa,SD,2024-12-31,NaN

In [431]:
zillow_rental_price_2018_2024[zillow_rental_price_2018_2024['Region_Type'].str.contains('country')]

Empty DataFrame
Columns: [Region_ID, Size_Rank, Region_Name, Region_Type, State_Name, Date, Median_Rent_Price]
Index: []

In [432]:
zillow_rental_price_2018_2024 = zillow_rental_price_2018_2024.copy()
zillow_rental_price_2018_2024.loc[:, 'Year'] = zillow_rental_price_2018_2024['Date'].astype(str).str[:4].astype(int)

In [433]:
zillow_rental_price_2018_2024 = zillow_rental_price_2018_2024[['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name', 'Year', 'Median_Rent_Price']]

In [434]:
zillow_rental_price_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Median_Rent_Price
1,394913,1,"New York, NY",msa,NY,2018,2294.014898
2,753899,2,"Los Angeles, CA",msa,CA,2018,2086.965744
3,394463,3,"Chicago, IL",msa,IL,2018,1434.379932
4,394514,4,"Dallas, TX",msa,TX,2018,1210.774226
5,394692,5,"Houston, TX",msa,TX,2018,1274.087578
...,...,...,...,...,...,...,...
57619,394805,916,"Los Alamos, NM",msa,NM,2024,NaN
57620,394330,920,"Andrews, TX",msa,TX,2024,NaN
57621,786253,921,"Brownsville, TN",msa,TN,2024,NaN
57622,395104,926,"Snyder, TX",msa,TX,2024,NaN
57623,395186,932,"Vermillion, SD",msa,SD,2024,NaN

In [435]:
zillow_rental_price_2018_2024.duplicated().sum()

np.int64(23523)

In [436]:
zillow_rental_price_2018_2024 = zillow_rental_price_2018_2024.drop_duplicates()

In [437]:
zillow_rental_price_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Median_Rent_Price
1,394913,1,"New York, NY",msa,NY,2018,2294.014898
2,753899,2,"Los Angeles, CA",msa,CA,2018,2086.965744
3,394463,3,"Chicago, IL",msa,IL,2018,1434.379932
4,394514,4,"Dallas, TX",msa,TX,2018,1210.774226
5,394692,5,"Houston, TX",msa,TX,2018,1274.087578
...,...,...,...,...,...,...,...
57599,394751,821,"Kirksville, MO",msa,MO,2024,839.067247
57604,394758,852,"La Grande, OR",msa,OR,2024,1266.767362
57609,395004,872,"Prineville, OR",msa,OR,2024,1622.433022
57613,395198,882,"Wahpeton, ND",msa,ND,2024,831.231642
57618,394996,915,"Portales, NM",msa,NM,2024,949.540519

In [438]:
# Average monthly rental price per metro per year
metro_avg_rental_price = zillow_rental_price_2018_2024.groupby(['Region_Name', 'State_Name', 'Year'])['Median_Rent_Price'].mean().reset_index()
metro_avg_rental_price

         Region_Name State_Name  Year  Median_Rent_Price
0       Aberdeen, SD         SD  2018                NaN
1       Aberdeen, SD         SD  2019                NaN
2       Aberdeen, SD         SD  2020                NaN
3       Aberdeen, SD         SD  2021                NaN
4       Aberdeen, SD         SD  2022                NaN
...              ...        ...   ...                ...
4790  Zanesville, OH         OH  2020                NaN
4791  Zanesville, OH         OH  2021                NaN
4792  Zanesville, OH         OH  2022                NaN
4793  Zanesville, OH         OH  2023         852.985267
4794  Zanesville, OH         OH  2024         888.314793

[4795 rows x 4 columns]

In [439]:
# Mean across metros to get state totals
state_totals_rental_price = metro_avg_rental_price.groupby(['State_Name','Year'])['Median_Rent_Price'].mean().reset_index()
state_totals_rental_price

    State_Name  Year  Median_Rent_Price
0           AK  2018        1184.985788
1           AK  2019        1199.214250
2           AK  2020        1225.571045
3           AK  2021        1386.856358
4           AK  2022        1500.786436
..         ...   ...                ...
345         WY  2020         968.464261
346         WY  2021        1001.732737
347         WY  2022        1092.072283
348         WY  2023        1174.064030
349         WY  2024        1630.987177

[350 rows x 3 columns]

In [440]:
state_totals_rental_price.groupby('Year')['Median_Rent_Price'].mean()

Year
2018    1089.403136
2019    1132.621352
2020    1177.034618
2021    1279.075137
2022    1385.011931
2023    1429.718884
2024    1484.323221
Name: Median_Rent_Price, dtype: float64

In [441]:
zillow_rental_price_2018_2024 = state_totals_rental_price.copy()

In [442]:
zillow_rental_price_2018_2024

    State_Name  Year  Median_Rent_Price
0           AK  2018        1184.985788
1           AK  2019        1199.214250
2           AK  2020        1225.571045
3           AK  2021        1386.856358
4           AK  2022        1500.786436
..         ...   ...                ...
345         WY  2020         968.464261
346         WY  2021        1001.732737
347         WY  2022        1092.072283
348         WY  2023        1174.064030
349         WY  2024        1630.987177

[350 rows x 3 columns]

In [443]:
# saved zillow_rental_price_2018_2024 as rental_price_2018_2024
zillow_rental_price_2018_2024.to_csv('rental_price_2018_2024.csv', index=False)

-----------------------------------------------------------------------------------------------------------------------------------

# Data Cleaning for United States zillow home value from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [19]:
zillow_home_value_2000_2025 = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/zillow-home-value.csv")
zillow_home_value_2000_2025

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
0,102001,0,United States,country,NaN,120438.319923,120650.209537,120912.983858,121476.583196,122125.218463,...,357612.951205,357092.990063,356417.996510,355810.294479,355390.262173,355166.149594,355403.981336,355831.508982,356496.909241,357275.367233
1,394913,1,"New York, NY",msa,NY,216079.651603,216997.868206,217924.589149,219802.484377,221747.109917,...,681693.678562,684104.823766,685856.506483,687317.851217,688479.047533,689261.406036,690648.448485,692961.405617,696271.386684,699658.379149
2,753899,2,"Los Angeles, CA",msa,CA,218371.605743,219184.225184,220266.626529,222420.241601,224775.621328,...,943203.974273,938949.357513,934245.245616,929954.117322,927399.461277,926343.623500,927385.106343,929766.414358,933035.896593,936938.582436
3,394463,3,"Chicago, IL",msa,IL,150621.346426,150760.777915,151026.327642,151686.949370,152481.597849,...,324946.583187,325536.495524,325821.754976,326176.067308,326999.945994,327977.388591,329285.901364,330566.688185,332085.845226,333786.344335
4,394514,4,"Dallas, TX",msa,TX,126453.664887,126509.987791,126574.736735,126742.882942,126964.579111,...,369732.296582,367624.873396,365231.083313,362888.919726,360890.913402,359541.413933,358900.323816,358554.951977,358293.726281,358078.023328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,753929,935,"Zapata, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,130976.382095,128909.049182,126652.043819,124519.630429,123796.787658,123346.005018,122589.348973,121620.664758,120842.653325,120803.924158
891,394743,936,"Ketchikan, AK",msa,AK,NaN,NaN,NaN,NaN,NaN,...,351000.283549,352573.790742,355431.282266,359350.504765,363274.880043,367335.056288,370710.985083,373936.877368,376268.670317,378260.716733
892,753874,937,"Craig, CO",msa,CO,97474.616440,97723.865851,98187.902960,98848.734667,99616.666347,...,290243.693794,291501.518796,292876.053510,293921.919213,295058.864598,296058.908522,297300.265561,297587.232536,297148.627413,296653.719069
893,395188,938,"Vernon, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,94781.135120,93359.072372,92213.835050,91376.451133,90793.238724,90541.411997,90195.232627,90005.494382,90468.272477,91348.202071
894,394767,939,"Lamesa, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,100904.362375,101212.902465,101084.356230,100954.931541,100948.376227,100713.411276,100660.071119,100957.207963,102215.766354,104422.800718

In [445]:
zillow_home_value_2000_2025.dtypes

RegionID        int64
SizeRank        int64
RegionName        str
RegionType        str
StateName         str
               ...
2025-08-31    float64
2025-09-30    float64
2025-10-31    float64
2025-11-30    float64
2025-12-31    float64
Length: 317, dtype: object

In [446]:
# Convert column names to datetime where possible

data = zillow_home_value_2000_2025

# Convert columns to datetime where possible
date_cols = pd.to_datetime(data.columns,format='%Y-%m-%d', errors='coerce')

start_date = pd.to_datetime('2018-01-01')
end_date = pd.to_datetime('2024-12-31')

date_mask = (date_cols >= start_date) & (date_cols <= end_date)

# Select only valid date columns
selected_date_cols = data.columns[date_mask]

# ID columns (already a list)

id_cols = ['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name']
data = data.rename(columns={
    'RegionID': 'Region_ID',
    'SizeRank': 'Size_Rank',
    'RegionName': 'Region_Name',
    'RegionType': 'Region_Type',
    'StateName': 'State_Name'
})

# Combine them correctly
df_filtered = data[id_cols + selected_date_cols.tolist()]
df_filtered

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,...,2024-03-31,2024-04-30,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31
0,102001,0,United States,country,NaN,220152.553308,221346.898082,222728.471205,223986.446808,225208.481919,...,350409.270764,352238.659952,353651.752075,354205.264043,354351.169555,354591.033181,355035.140028,355615.197184,356101.135345,356810.756530
1,394913,1,"New York, NY",msa,NY,465876.491346,467418.475328,469203.875893,471073.186896,473641.608247,...,645273.258073,651371.933924,656023.151924,659098.833548,661840.908631,665577.470067,669597.391558,673115.701761,675881.658716,677662.884511
2,753899,2,"Los Angeles, CA",msa,CA,591089.335557,598940.316503,606396.823543,612074.444505,616626.355698,...,907110.394103,910539.302934,916368.370035,920279.716950,924609.841676,929741.009717,936097.506189,941264.869369,945717.092425,949696.699511
3,394463,3,"Chicago, IL",msa,IL,223091.599695,224424.250421,225963.694928,227166.882468,228108.475348,...,309541.691580,312363.683490,314447.423946,315649.744079,316373.197646,317279.472303,318265.734005,319226.846061,320247.681034,321473.825865
4,394514,4,"Dallas, TX",msa,TX,236413.849052,238238.412918,240080.880554,241723.648479,243267.681961,...,374789.046056,375760.651555,375904.890202,375238.563062,374297.216566,373644.069454,373445.723253,373339.570527,373050.522480,372525.228854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,753929,935,"Zapata, TX",msa,TX,132358.110945,131825.012780,132218.888407,133196.724796,134072.044050,...,131089.737108,132729.098708,134588.314460,135772.067646,136001.204964,135638.692055,134975.860875,134051.938909,133247.898094,132667.292715
891,394743,936,"Ketchikan, AK",msa,AK,261214.266237,263001.293654,265755.526820,268510.314048,270486.649735,...,343363.078212,344711.534539,345706.453057,345767.785587,345088.352265,345043.429644,346220.203584,347914.570746,348369.732024,348713.664743
892,753874,937,"Craig, CO",msa,CO,165559.776626,166238.242470,167099.507643,167334.339816,167101.824661,...,281078.658579,281849.050143,282739.800700,283074.626763,283393.887157,283619.246376,284961.899132,286636.911768,287844.087145,288891.015570
893,395188,938,"Vernon, TX",msa,TX,80768.093669,81097.215036,81921.259150,82717.760041,83355.389534,...,103721.521937,104560.796370,105297.328157,105594.913105,105365.339886,104817.684720,103383.284507,101575.330579,99397.254542,97946.283187
894,394767,939,"Lamesa, TX",msa,TX,93346.870599,93492.569912,94396.313752,95054.087213,95547.533985,...,94539.148855,94776.331920,95774.838823,97165.323305,99136.671995,100898.397828,101662.682044,101673.098215,101140.817049,100790.893670

In [447]:
zillow_home_value_2018_2024 = df_filtered.melt(
    id_vars=id_cols,
    var_name='Date',
    value_name='Median_Home_Value'
)

zillow_home_value_2018_2024['Date'] = pd.to_datetime(zillow_home_value_2018_2024['Date'])
zillow_home_value_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Median_Home_Value
0,102001,0,United States,country,NaN,2018-01-31,220152.553308
1,394913,1,"New York, NY",msa,NY,2018-01-31,465876.491346
2,753899,2,"Los Angeles, CA",msa,CA,2018-01-31,591089.335557
3,394463,3,"Chicago, IL",msa,IL,2018-01-31,223091.599695
4,394514,4,"Dallas, TX",msa,TX,2018-01-31,236413.849052
...,...,...,...,...,...,...,...
75175,753929,935,"Zapata, TX",msa,TX,2024-12-31,132667.292715
75176,394743,936,"Ketchikan, AK",msa,AK,2024-12-31,348713.664743
75177,753874,937,"Craig, CO",msa,CO,2024-12-31,288891.015570
75178,395188,938,"Vernon, TX",msa,TX,2024-12-31,97946.283187
75179,394767,939,"Lamesa, TX",msa,TX,2024-12-31,100790.893670

In [448]:
zillow_home_value_2018_2024 = zillow_home_value_2018_2024[~zillow_home_value_2018_2024['Region_Type'].str.contains('country')]

In [449]:
zillow_home_value_2018_2024.head(2)

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Median_Home_Value
1,394913,1,"New York, NY",msa,NY,2018-01-31,465876.491346
2,753899,2,"Los Angeles, CA",msa,CA,2018-01-31,591089.335557

In [450]:
zillow_home_value_2018_2024 = zillow_home_value_2018_2024.copy()
zillow_home_value_2018_2024.loc[:, 'Year'] = zillow_home_value_2018_2024['Date'].astype(str).str[:4].astype(int)

In [451]:
zillow_home_value_2018_2024 = zillow_home_value_2018_2024[['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name', 'Year', 'Median_Home_Value']]

In [452]:
zillow_home_value_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Median_Home_Value
1,394913,1,"New York, NY",msa,NY,2018,465876.491346
2,753899,2,"Los Angeles, CA",msa,CA,2018,591089.335557
3,394463,3,"Chicago, IL",msa,IL,2018,223091.599695
4,394514,4,"Dallas, TX",msa,TX,2018,236413.849052
5,394692,5,"Houston, TX",msa,TX,2018,207758.727596
...,...,...,...,...,...,...,...
75175,753929,935,"Zapata, TX",msa,TX,2024,132667.292715
75176,394743,936,"Ketchikan, AK",msa,AK,2024,348713.664743
75177,753874,937,"Craig, CO",msa,CO,2024,288891.015570
75178,395188,938,"Vernon, TX",msa,TX,2024,97946.283187
75179,394767,939,"Lamesa, TX",msa,TX,2024,100790.893670

In [453]:
zillow_home_value_2018_2024.duplicated().sum()

np.int64(20)

In [454]:
zillow_home_value_2018_2024 = zillow_home_value_2018_2024.drop_duplicates()

In [455]:
zillow_home_value_2018_2024.duplicated().sum()

np.int64(0)

In [456]:
# Average monthly home value per metro per year
metro_avg_home_value = zillow_home_value_2018_2024.groupby(['Region_Name','State_Name','Year'])['Median_Home_Value'].mean().reset_index()
metro_avg_home_value

       Region_Name State_Name  Year  Median_Home_Value
0     Aberdeen, SD         SD  2018      152967.841101
1     Aberdeen, SD         SD  2019      160091.396441
2     Aberdeen, SD         SD  2020      169474.298539
3     Aberdeen, SD         SD  2021      186535.245165
4     Aberdeen, SD         SD  2022      204422.052631
...            ...        ...   ...                ...
6253    Zapata, TX         TX  2020      146960.107675
6254    Zapata, TX         TX  2021      160154.497700
6255    Zapata, TX         TX  2022      160721.797255
6256    Zapata, TX         TX  2023      140536.677891
6257    Zapata, TX         TX  2024      133631.789145

[6258 rows x 4 columns]

In [457]:
# Mean across metros to get state totals
state_totals_home_value = metro_avg_home_value.groupby(['State_Name','Year'])['Median_Home_Value'].mean().reset_index()
state_totals_home_value

    State_Name  Year  Median_Home_Value
0           AK  2018      292855.925684
1           AK  2019      306141.400620
2           AK  2020      317136.642502
3           AK  2021      334507.770729
4           AK  2022      356421.134816
..         ...   ...                ...
345         WY  2020      305284.297336
346         WY  2021      350311.948170
347         WY  2022      404896.708549
348         WY  2023      421802.402918
349         WY  2024      437619.127898

[350 rows x 3 columns]

In [458]:
state_totals_home_value.groupby('Year')['Median_Home_Value'].mean()

Year
2018    208037.969644
2019    218011.485150
2020    231980.219055
2021    268090.766552
2022    305508.092061
2023    312440.866106
2024    324560.195169
Name: Median_Home_Value, dtype: float64

In [459]:
zillow_home_value_2018_2024 = state_totals_home_value.copy()

In [460]:
state_totals_home_value.head()

  State_Name  Year  Median_Home_Value
0         AK  2018      292855.925684
1         AK  2019      306141.400620
2         AK  2020      317136.642502
3         AK  2021      334507.770729
4         AK  2022      356421.134816

In [461]:
# saved zillow_home_value_2018_2024 as home_value_2018_2024.csv
zillow_home_value_2018_2024.to_csv('home_value_2018_2024.csv', index=False)

# Data Cleaning for United States zillow home value from 2015-2024
- Droped unnecessary index
- Reset index
- Change column names
- Removed unnecessary columns
- Data standardaziation
- Check for data consistency

In [21]:
zillow_sales_count_2008_2026  = pd.read_csv("D:/project folder/US-Housing-Market-and-Affordability-Crisis-Project/dataset/raw-data/zillow-sales-count.csv")
zillow_sales_count_2008_2026

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
0,102001,0,United States,country,NaN,203871.0,235974.0,261775.0,288739.0,301809.0,...,351859.0,359351.0,357221.0,341314.0,326624.0,331619.0,263573.0,301883.0,212896.0,229808.0
1,394913,1,"New York, NY",msa,NY,8530.0,9053.0,10042.0,10472.0,11324.0,...,12433.0,13588.0,14841.0,14367.0,13791.0,13624.0,11124.0,13337.0,9449.0,8140.0
2,753899,2,"Los Angeles, CA",msa,CA,4138.0,5049.0,6077.0,6864.0,7220.0,...,6720.0,6622.0,6984.0,6503.0,6643.0,7003.0,5393.0,6131.0,4435.0,4926.0
3,394463,3,"Chicago, IL",msa,IL,5606.0,6961.0,7320.0,7991.0,8818.0,...,9537.0,10413.0,10153.0,9270.0,8540.0,8770.0,6575.0,7469.0,5274.0,5947.0
4,394514,4,"Dallas, TX",msa,TX,4921.0,5585.0,6033.0,6727.0,6716.0,...,7205.0,7072.0,7155.0,6582.0,6054.0,6035.0,4727.0,5729.0,4077.0,4872.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,394928,410,"Ocean City, NJ",msa,NJ,161.0,224.0,248.0,281.0,261.0,...,364.0,356.0,249.0,314.0,351.0,417.0,268.0,309.0,264.0,193.0
297,394744,442,"Key West, FL",msa,FL,93.0,113.0,106.0,116.0,122.0,...,193.0,192.0,171.0,150.0,151.0,142.0,124.0,148.0,117.0,139.0
298,394674,467,"Heber, UT",msa,UT,60.0,62.0,76.0,71.0,65.0,...,167.0,199.0,228.0,248.0,221.0,236.0,161.0,188.0,109.0,136.0
299,394877,491,"Morehead City, NC",msa,NC,77.0,80.0,97.0,109.0,104.0,...,151.0,156.0,158.0,174.0,132.0,133.0,118.0,124.0,86.0,105.0
300,394745,744,"Kill Devil Hills, NC",msa,NC,67.0,78.0,64.0,91.0,89.0,...,216.0,201.0,185.0,201.0,191.0,171.0,136.0,184.0,126.0,120.0

In [463]:
zillow_sales_count_2008_2026.dtypes

RegionID        int64
SizeRank        int64
RegionName        str
RegionType        str
StateName         str
               ...
2025-10-31    float64
2025-11-30    float64
2025-12-31    float64
2026-01-31    float64
2026-02-28    float64
Length: 222, dtype: object

In [464]:
zillow_sales_count_2008_2026.describe()

,RegionID,SizeRank,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
count,301.000000,301.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,296.000000,...,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000
mean,408153.275748,161.308970,1278.334459,1484.942568,1646.570946,1814.236486,1900.918919,1916.239865,1805.929054,1700.682432,...,2159.963455,2202.857143,2186.986711,2080.392027,1988.375415,2022.358804,1611.176080,1847.534884,1305.079734,1418.561462
std,76289.762029,107.040869,11858.876562,13725.192186,15225.538562,16791.381092,17553.609650,17723.605033,16734.917722,15753.751748,...,20286.915228,20720.468214,20598.801137,19680.058001,18832.860341,19120.572072,15197.714073,17408.710993,12277.076397,13250.855230
min,102001.000000,0.000000,36.000000,44.000000,40.000000,55.000000,51.000000,49.000000,49.000000,39.000000,...,125.000000,127.000000,119.000000,123.000000,112.000000,114.000000,94.000000,110.000000,77.000000,78.000000
25%,394553.000000,76.000000,132.000000,150.750000,169.750000,188.500000,200.250000,185.250000,184.750000,163.000000,...,226.000000,231.000000,228.000000,228.000000,214.000000,217.000000,175.000000,198.000000,140.000000,147.000000
50%,394807.000000,152.000000,234.500000,278.500000,296.000000,348.000000,360.500000,356.500000,333.000000,305.000000,...,412.000000,424.000000,425.000000,393.000000,390.000000,384.000000,321.000000,352.000000,249.000000,283.000000
75%,395056.000000,232.000000,548.750000,594.250000,689.750000,775.250000,798.500000,787.500000,717.000000,664.250000,...,910.000000,907.000000,881.000000,842.000000,834.000000,825.000000,677.000000,795.000000,550.000000,581.000000
max,845164.000000,744.000000,203871.000000,235974.000000,261775.000000,288739.000000,301809.000000,304619.000000,287662.000000,270761.000000,...,351859.000000,359351.000000,357221.000000,341314.000000,326624.000000,331619.000000,263573.000000,301883.000000,212896.000000,229808.000000

In [465]:
zillow_sales_count_2008_2026.duplicated().sum()

np.int64(0)

In [466]:
zillow_sales_count_2008_2026.isna().sum()

RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2025-10-31    0
2025-11-30    0
2025-12-31    0
2026-01-31    0
2026-02-28    0
Length: 222, dtype: int64

In [467]:
# Columns that are NOT dates (keep these fixed), change column names
id_cols = ['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName']
new_cols = ['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type', 'State_Name']

zillow_sales_count_2008_2026 = zillow_sales_count_2008_2026.rename(columns=dict(zip(id_cols, new_cols)))

# Melt the dataframe
zillow_sales_count_2008_2026 = zillow_sales_count_2008_2026.melt(
    id_vars=new_cols,
    var_name='Date',
    value_name='Sales_Count'
)


# Convert Date column to datetime
zillow_sales_count_2008_2026['Date'] = pd.to_datetime(zillow_sales_count_2008_2026['Date'])

# View result
zillow_sales_count_2008_2026.head()

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Date,Sales_Count
0,102001,0,United States,country,NaN,2008-02-29,203871.0
1,394913,1,"New York, NY",msa,NY,2008-02-29,8530.0
2,753899,2,"Los Angeles, CA",msa,CA,2008-02-29,4138.0
3,394463,3,"Chicago, IL",msa,IL,2008-02-29,5606.0
4,394514,4,"Dallas, TX",msa,TX,2008-02-29,4921.0

In [468]:
zillow_sales_count_2008_2026 = zillow_sales_count_2008_2026.copy()
zillow_sales_count_2008_2026.loc[:, 'Year'] = zillow_sales_count_2008_2026['Date'].astype(str).str[:4].astype(int)

In [469]:
zillow_sales_count_2008_2026 = zillow_sales_count_2008_2026[['Region_ID', 
                                                         'Size_Rank', 
                                                         'Region_Name', 
                                                         'Region_Type', 
                                                         'State_Name', 
                                                         'Year', 
                                                         'Sales_Count']]

In [470]:
zillow_sales_count_2008_2026.head()

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
0,102001,0,United States,country,NaN,2008,203871.0
1,394913,1,"New York, NY",msa,NY,2008,8530.0
2,753899,2,"Los Angeles, CA",msa,CA,2008,4138.0
3,394463,3,"Chicago, IL",msa,IL,2008,5606.0
4,394514,4,"Dallas, TX",msa,TX,2008,4921.0

In [471]:
zillow_sales_count_2008_2026[zillow_sales_count_2008_2026['Region_Type'].str.contains('country')]

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
0,102001,0,United States,country,NaN,2008,203871.0
301,102001,0,United States,country,NaN,2008,235974.0
602,102001,0,United States,country,NaN,2008,261775.0
903,102001,0,United States,country,NaN,2008,288739.0
1204,102001,0,United States,country,NaN,2008,301809.0
...,...,...,...,...,...,...,...
63812,102001,0,United States,country,NaN,2025,331619.0
64113,102001,0,United States,country,NaN,2025,263573.0
64414,102001,0,United States,country,NaN,2025,301883.0
64715,102001,0,United States,country,NaN,2026,212896.0
65016,102001,0,United States,country,NaN,2026,229808.0

In [472]:
zillow_sales_count_2008_2026 = zillow_sales_count_2008_2026[~zillow_sales_count_2008_2026['Region_Type'].str.contains('country')]

In [473]:
zillow_sales_count_2008_2026[zillow_sales_count_2008_2026['Region_Type']=='country']

Empty DataFrame
Columns: [Region_ID, Size_Rank, Region_Name, Region_Type, State_Name, Year, Sales_Count]
Index: []

In [474]:
zillow_sales_count_2008_2026.head(2)

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
1,394913,1,"New York, NY",msa,NY,2008,8530.0
2,753899,2,"Los Angeles, CA",msa,CA,2008,4138.0

In [475]:
# remove from 2008-2017 and from 2025-2026 rows and rename it to zillow_sales_count_2018_2024
zillow_sales_count_2018_2024 = zillow_sales_count_2008_2026.loc[(zillow_sales_count_2008_2026['Year'] >= 2018) & (zillow_sales_count_2008_2026['Year'] <= 2024)]

In [476]:
zillow_sales_count_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
35820,394913,1,"New York, NY",msa,NY,2018,14471.0
35821,753899,2,"Los Angeles, CA",msa,CA,2018,6835.0
35822,394463,3,"Chicago, IL",msa,IL,2018,7428.0
35823,394514,4,"Dallas, TX",msa,TX,2018,5278.0
35824,394692,5,"Houston, TX",msa,TX,2018,4730.0
...,...,...,...,...,...,...,...
61098,394928,410,"Ocean City, NJ",msa,NJ,2024,244.0
61099,394744,442,"Key West, FL",msa,FL,2024,97.0
61100,394674,467,"Heber, UT",msa,UT,2024,175.0
61101,394877,491,"Morehead City, NC",msa,NC,2024,130.0
61102,394745,744,"Kill Devil Hills, NC",msa,NC,2024,175.0

In [477]:
zillow_sales_count_2018_2024.duplicated().sum()

np.int64(511)

In [478]:
zillow_sales_count_2018_2024 = zillow_sales_count_2018_2024.drop_duplicates()

In [479]:
zillow_sales_count_2018_2024

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
35820,394913,1,"New York, NY",msa,NY,2018,14471.0
35821,753899,2,"Los Angeles, CA",msa,CA,2018,6835.0
35822,394463,3,"Chicago, IL",msa,IL,2018,7428.0
35823,394514,4,"Dallas, TX",msa,TX,2018,5278.0
35824,394692,5,"Houston, TX",msa,TX,2018,4730.0
...,...,...,...,...,...,...,...
61098,394928,410,"Ocean City, NJ",msa,NJ,2024,244.0
61099,394744,442,"Key West, FL",msa,FL,2024,97.0
61100,394674,467,"Heber, UT",msa,UT,2024,175.0
61101,394877,491,"Morehead City, NC",msa,NC,2024,130.0
61102,394745,744,"Kill Devil Hills, NC",msa,NC,2024,175.0

In [480]:
# Average monthly sales count per metro per year
metro_avg_sales_count = zillow_sales_count_2018_2024.groupby(['Region_Name', 'State_Name', 'Year'])['Sales_Count'].sum().reset_index()
metro_avg_sales_count

      Region_Name State_Name  Year  Sales_Count
0     Abilene, TX         TX  2018       2236.0
1     Abilene, TX         TX  2019       2171.0
2     Abilene, TX         TX  2020       2509.0
3     Abilene, TX         TX  2021       2632.0
4     Abilene, TX         TX  2022       2223.0
...           ...        ...   ...          ...
2095     Yuma, AZ         AZ  2020       2907.0
2096     Yuma, AZ         AZ  2021       3432.0
2097     Yuma, AZ         AZ  2022       2563.0
2098     Yuma, AZ         AZ  2023       1900.0
2099     Yuma, AZ         AZ  2024       1916.0

[2100 rows x 4 columns]

In [481]:
# Mean across metros to get state totals
state_totals_sales_count = metro_avg_sales_count.groupby(['State_Name','Year'])['Sales_Count'].sum().reset_index()
state_totals_sales_count

    State_Name  Year  Sales_Count
0           AK  2018       5016.0
1           AK  2019       5462.0
2           AK  2020       5693.0
3           AK  2021       6700.0
4           AK  2022       5643.0
..         ...   ...          ...
338         WV  2020       2577.0
339         WV  2021       2589.0
340         WV  2022       2102.0
341         WV  2023       2169.0
342         WV  2024       2252.0

[343 rows x 3 columns]

In [482]:
state_totals_sales_count.groupby('Year')['Sales_Count'].sum()

Year
2018    4003402.0
2019    3959699.0
2020    4168096.0
2021    4955066.0
2022    4019103.0
2023    3066975.0
2024    3038713.0
Name: Sales_Count, dtype: float64

In [483]:
zillow_sales_count_2018_2024 = state_totals_sales_count.copy()

In [484]:
# saved zillow_sales_count_2018_2024 as sales_count_2018_2024.csv
zillow_sales_count_2018_2024.to_csv('sales_count_2018_2024.csv', index=False)

### Data Reconciliation Result

After a detailed review and data validation process, there was no **data discrepancy**

#### Final Outcome
- All relevant records were confirmed to be consistently included in both platforms.
- Data types, filters, and missing-value handling were corrected in Python.
- Recalculated metrics (including minimum, maximum, and total values) now match exactly.

**Conclusion:**  
There is **no data discrepancy** between Excel and Python. All computed values are consistent across both tools, confirming the accuracy and integrity of the dataset.