In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize']=(12,8)

In [2]:
census_income = pd.read_csv('census_income_2018_2024.csv')
home_value = pd.read_csv('home_value_2018_2024.csv')
mortgage_rate = pd.read_csv('mortgage_2018_2024.csv')
pop_growth = pd.read_csv('pop_growth_2018_2024.csv')
consumer_price_index = pd.read_csv('cpi_2018_2024.csv')
inventory = pd.read_csv('inventory_2018_2024.csv')
rental_price = pd.read_csv('rental_price_2018_2024.csv')
household_estimate = pd.read_csv('household_estimate_2018_2024.csv')
sales_count = pd.read_csv('sales_count_2018_2024')

In [262]:
census_income.head(10)

   Year State_Name  Median_Income
0  2018         AK          84540
1  2019         AK          95010
2  2020         AK          89650
3  2021         AK          93150
4  2022         AK          95670
5  2023         AK         100700
6  2024         AK          91260
7  2018         AL          61420
8  2019         AL          68110
9  2020         AL          65600

In [263]:
home_value.head(2)

  State_Name  Year  Median_Home_Value
0         AK  2018      292855.925684
1         AK  2019      306141.400620

In [265]:
home_value = home_value.groupby(['State_Name', 'Year']).agg({'Median_Home_Value': 'median'})

In [266]:
affordability_base_2018_2024 = home_value.merge(census_income, how='left', on=['Year','State_Name'])
affordability_base_2018_2024

     Year State_Name  Median_Home_Value  Median_Income
0    2018         AK      292855.925684          84540
1    2019         AK      306141.400620          95010
2    2020         AK      317136.642502          89650
3    2021         AK      334507.770729          93150
4    2022         AK      356421.134816          95670
..    ...        ...                ...            ...
345  2020         WY      305284.297336          78500
346  2021         WY      350311.948170          81580
347  2022         WY      404896.708549          77920
348  2023         WY      421802.402918          79200
349  2024         WY      437619.127898          78680

[350 rows x 4 columns]

In [267]:
affordability_base_2018_2024.head(30)

    Year State_Name  Median_Home_Value  Median_Income
0   2018         AK      292855.925684          84540
1   2019         AK      306141.400620          95010
2   2020         AK      317136.642502          89650
3   2021         AK      334507.770729          93150
4   2022         AK      356421.134816          95670
5   2023         AK      358097.619293         100700
6   2024         AK      363466.526295          91260
7   2018         AL      138391.021859          61420
8   2019         AL      145333.040507          68110
9   2020         AL      156389.809857          65600
10  2021         AL      176436.486012          65360
11  2022         AL      197708.554710          63870
12  2023         AL      203023.502795          62230
13  2024         AL      207991.397569          65560
14  2018         AR      119356.440076          61230
15  2019         AR      123678.558525          66100
16  2020         AR      131854.628682          60900
17  2021         AR      147787.318524          58310
18  2022         AR      162186.371876          57540
19  2023         AR      165087.061470          64880
20  2024         AR      169444.707339          64840
21  2018         AZ      207533.997953          76600
22  2019         AZ      223521.753355          85650
23  2020         AZ      243981.926164          80470
24  2021         AZ      296395.251167          81310
25  2022         AZ      350000.354871          78300
26  2023         AZ      347264.573441          84800
27  2024         AZ      358126.174166          84700
28  2018         CA      425566.111288          86690
29  2019         CA      438592.643993          94660

In [268]:
affordability_base_2018_2024[affordability_base_2018_2024['State_Name']=='CA']

    Year State_Name  Median_Home_Value  Median_Income
28  2018         CA      425566.111288          86690
29  2019         CA      438592.643993          94660
30  2020         CA      457611.477943          93140
31  2021         CA      528182.177264          93660
32  2022         CA      593903.693955          90930
33  2023         CA      580671.771655          92200
34  2024         CA      601193.344989         100600

In [269]:
affordability_base_2018_2024[affordability_base_2018_2024['State_Name']=='CA']

    Year State_Name  Median_Home_Value  Median_Income
28  2018         CA      425566.111288          86690
29  2019         CA      438592.643993          94660
30  2020         CA      457611.477943          93140
31  2021         CA      528182.177264          93660
32  2022         CA      593903.693955          90930
33  2023         CA      580671.771655          92200
34  2024         CA      601193.344989         100600

In [270]:
affordability_base_2018_2024['Price_To_Income'] = affordability_base_2018_2024['Median_Home_Value'] / affordability_base_2018_2024['Median_Income']

In [271]:
# The median home costs about 3.46 times the median household income on AK in the year 2018.
affordability_base_2018_2024

     Year State_Name  Median_Home_Value  Median_Income  Price_To_Income
0    2018         AK      292855.925684          84540         3.464111
1    2019         AK      306141.400620          95010         3.222202
2    2020         AK      317136.642502          89650         3.537497
3    2021         AK      334507.770729          93150         3.591066
4    2022         AK      356421.134816          95670         3.725527
..    ...        ...                ...            ...              ...
345  2020         WY      305284.297336          78500         3.888972
346  2021         WY      350311.948170          81580         4.294091
347  2022         WY      404896.708549          77920         5.196313
348  2023         WY      421802.402918          79200         5.325788
349  2024         WY      437619.127898          78680         5.562012

[350 rows x 5 columns]

In [272]:
affordability_base_2018_2024

     Year State_Name  Median_Home_Value  Median_Income  Price_To_Income
0    2018         AK      292855.925684          84540         3.464111
1    2019         AK      306141.400620          95010         3.222202
2    2020         AK      317136.642502          89650         3.537497
3    2021         AK      334507.770729          93150         3.591066
4    2022         AK      356421.134816          95670         3.725527
..    ...        ...                ...            ...              ...
345  2020         WY      305284.297336          78500         3.888972
346  2021         WY      350311.948170          81580         4.294091
347  2022         WY      404896.708549          77920         5.196313
348  2023         WY      421802.402918          79200         5.325788
349  2024         WY      437619.127898          78680         5.562012

[350 rows x 5 columns]

In [273]:
affordability_base_2018_2024 = (affordability_base_2018_2024
 .groupby(['State_Name','Year']).agg({'Median_Home_Value': 'median',
                                    'Median_Income': 'median',
                                    'Price_To_Income': 'mean'})).reset_index()
affordability_base_2018_2024

    State_Name  Year  Median_Home_Value  Median_Income  Price_To_Income
0           AK  2018      292855.925684        84540.0         3.464111
1           AK  2019      306141.400620        95010.0         3.222202
2           AK  2020      317136.642502        89650.0         3.537497
3           AK  2021      334507.770729        93150.0         3.591066
4           AK  2022      356421.134816        95670.0         3.725527
..         ...   ...                ...            ...              ...
345         WY  2020      305284.297336        78500.0         3.888972
346         WY  2021      350311.948170        81580.0         4.294091
347         WY  2022      404896.708549        77920.0         5.196313
348         WY  2023      421802.402918        79200.0         5.325788
349         WY  2024      437619.127898        78680.0         5.562012

[350 rows x 5 columns]

In [274]:
# rank state by affordability
state_affordability = (
    affordability_base_2018_2024
    .groupby('State_Name')['Price_To_Income']
    .mean()
    .reset_index()
    .sort_values('Price_To_Income')
)
state_affordability

   State_Name  Price_To_Income
13         IL         1.505802
15         KS         1.716492
34         OH         2.010795
35         OK         2.013752
11         IA         2.032369
14         IN         2.100685
28         NE         2.153842
37         PA         2.197063
23         MO         2.198741
48         WV         2.237964
33         NY         2.302222
2          AR         2.356636
21         MI         2.356887
22         MN         2.363986
42         TX         2.439004
9          GA         2.441850
16         KY         2.480725
44         VA         2.489784
19         MD         2.498055
24         MS         2.661762
1          AL         2.714418
47         WI         2.762638
17         LA         2.864574
29         NH         2.910668
27         ND         2.927996
41         TN         2.928191
39         SC         2.991219
40         SD         2.992550
26         NC         3.148190
20         ME         3.254360
30         NJ         3.363834
6          CT         3.376151
3          AZ         3.541358
0          AK         3.582749
45         VT         3.615203
7          DE         3.655383
31         NM         3.712134
46         WA         3.861292
36         OR         3.988851
43         UT         4.017587
8          FL         4.065440
38         RI         4.334181
12         ID         4.495086
49         WY         4.501715
32         NV         4.610766
25         MT         4.777799
5          CO         4.868569
18         MA         4.974946
4          CA         5.557199
10         HI         7.177436

In [275]:
mortgage_rate

   Year  Mortgage_Rate_pct
0  2018           4.539042
1  2019           3.933750
2  2020           3.113667
3  2021           2.955708
4  2022           5.327500
5  2023           6.795375
6  2024           6.723667

In [276]:
affordability_with_mortgage_2018_2024 = affordability_base_2018_2024.merge(mortgage_rate, how= 'left', on= 'Year')

In [277]:
affordability_with_mortgage_2018_2024

,State_Name,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct
0,AK,2018,292855.925684,84540.0,3.464111,4.539042
1,AK,2019,306141.400620,95010.0,3.222202,3.933750
2,AK,2020,317136.642502,89650.0,3.537497,3.113667
3,AK,2021,334507.770729,93150.0,3.591066,2.955708
4,AK,2022,356421.134816,95670.0,3.725527,5.327500
...,...,...,...,...,...,...
345,WY,2020,305284.297336,78500.0,3.888972,3.113667
346,WY,2021,350311.948170,81580.0,4.294091,2.955708
347,WY,2022,404896.708549,77920.0,5.196313,5.327500
348,WY,2023,421802.402918,79200.0,5.325788,6.795375
349,WY,2024,437619.127898,78680.0,5.562012,6.723667

In [278]:
rental_price

    State_Name  Year  Median_Rent_Price
0           AK  2018        1184.985788
1           AK  2019        1199.214250
2           AK  2020        1225.571045
3           AK  2021        1386.856358
4           AK  2022        1500.786436
..         ...   ...                ...
345         WY  2020         968.464261
346         WY  2021        1001.732737
347         WY  2022        1092.072283
348         WY  2023        1174.064030
349         WY  2024        1630.987177

[350 rows x 3 columns]

In [ ]:
rental_price = rental_price.groupby(['State_Name', 'Year']).agg({'Median_Rent_Price': 'median'})

In [280]:
rental_price

    State_Name  Year  Median_Rent_Price
0           AK  2018        1184.985788
1           AK  2019        1199.214250
2           AK  2020        1225.571045
3           AK  2021        1386.856358
4           AK  2022        1500.786436
..         ...   ...                ...
345         WY  2020         968.464261
346         WY  2021        1001.732737
347         WY  2022        1092.072283
348         WY  2023        1174.064030
349         WY  2024        1630.987177

[350 rows x 3 columns]

In [281]:
affordability_with_rent_2018_2024 = affordability_with_mortgage_2018_2024.merge(rental_price, how= 'left', on= ['State_Name','Year'])

In [282]:
affordability_with_rent_2018_2024

,State_Name,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price
0,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788
1,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250
2,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045
3,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358
4,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436
...,...,...,...,...,...,...,...
345,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261
346,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737
347,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283
348,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030
349,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177

In [283]:
affordability_with_rent_2018_2024.info(memory_usage=True)

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State_Name         350 non-null    str
 1   Year               350 non-null    int64
 2   Median_Home_Value  350 non-null    float64
 3   Median_Income      350 non-null    float64
 4   Price_To_Income    350 non-null    float64
 5   Mortgage_Rate_pct  350 non-null    float64
 6   Median_Rent_Price  350 non-null    float64
dtypes: float64(5), int64(1), str(1)
memory usage: 19.3 KB

In [284]:
inventory

    State_Name  Year  Active_Listings
0           AK  2018      2969.711111
1           AK  2019      2840.244949
2           AK  2020      2329.938889
3           AK  2021      1771.522222
4           AK  2022      1433.678788
..         ...   ...              ...
345         WY  2020      2357.069697
346         WY  2021      1803.892424
347         WY  2022      1760.998485
348         WY  2023      1841.687879
349         WY  2024      1889.562121

[350 rows x 3 columns]

In [286]:
inventory

    State_Name  Year  Active_Listings
0           AK  2018      2969.711111
1           AK  2019      2840.244949
2           AK  2020      2329.938889
3           AK  2021      1771.522222
4           AK  2022      1433.678788
..         ...   ...              ...
345         WY  2020      2357.069697
346         WY  2021      1803.892424
347         WY  2022      1760.998485
348         WY  2023      1841.687879
349         WY  2024      1889.562121

[350 rows x 3 columns]

In [287]:
inventory

    State_Name  Year  Active_Listings
0           AK  2018      2969.711111
1           AK  2019      2840.244949
2           AK  2020      2329.938889
3           AK  2021      1771.522222
4           AK  2022      1433.678788
..         ...   ...              ...
345         WY  2020      2357.069697
346         WY  2021      1803.892424
347         WY  2022      1760.998485
348         WY  2023      1841.687879
349         WY  2024      1889.562121

[350 rows x 3 columns]

In [288]:
inventory = inventory.groupby(['State_Name', 'Year']).agg({'Active_Listings': 'sum'}).reset_index()
inventory.head()

  State_Name  Year  Active_Listings
0         AK  2018      2969.711111
1         AK  2019      2840.244949
2         AK  2020      2329.938889
3         AK  2021      1771.522222
4         AK  2022      1433.678788

In [289]:
affordability_with_inventory_2018_2024 = affordability_with_rent_2018_2024.merge(inventory, how= 'left', on= ['State_Name', 'Year'])

In [290]:
affordability_with_inventory_2018_2024

,State_Name,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings
0,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111
1,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949
2,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889
3,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358,1771.522222
4,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436,1433.678788
...,...,...,...,...,...,...,...,...
345,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697
346,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424
347,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485
348,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879
349,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121

In [291]:
affordability_with_inventory_2018_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State_Name         350 non-null    str
 1   Year               350 non-null    int64
 2   Median_Home_Value  350 non-null    float64
 3   Median_Income      350 non-null    float64
 4   Price_To_Income    350 non-null    float64
 5   Mortgage_Rate_pct  350 non-null    float64
 6   Median_Rent_Price  350 non-null    float64
 7   Active_Listings    350 non-null    float64
dtypes: float64(6), int64(1), str(1)
memory usage: 22.0 KB

In [292]:
affordability_with_inventory_2018_2024.duplicated().sum()

np.int64(0)

In [293]:
affordability_with_inventory_2018_2024.drop_duplicates(inplace=True)

In [294]:
affordability_with_inventory_2018_2024.info(memory_usage=True)

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State_Name         350 non-null    str
 1   Year               350 non-null    int64
 2   Median_Home_Value  350 non-null    float64
 3   Median_Income      350 non-null    float64
 4   Price_To_Income    350 non-null    float64
 5   Mortgage_Rate_pct  350 non-null    float64
 6   Median_Rent_Price  350 non-null    float64
 7   Active_Listings    350 non-null    float64
dtypes: float64(6), int64(1), str(1)
memory usage: 22.0 KB

In [295]:
sales_count

,Region_ID,Size_Rank,Region_Name,Region_Type,State_Name,Year,Sales_Count
0,394913,1,"New York, NY",msa,NY,2018,14471.0
1,753899,2,"Los Angeles, CA",msa,CA,2018,6835.0
2,394463,3,"Chicago, IL",msa,IL,2018,7428.0
3,394514,4,"Dallas, TX",msa,TX,2018,5278.0
4,394692,5,"Houston, TX",msa,TX,2018,4730.0
...,...,...,...,...,...,...,...
25195,394928,410,"Ocean City, NJ",msa,NJ,2024,244.0
25196,394744,442,"Key West, FL",msa,FL,2024,97.0
25197,394674,467,"Heber, UT",msa,UT,2024,175.0
25198,394877,491,"Morehead City, NC",msa,NC,2024,130.0
25199,394745,744,"Kill Devil Hills, NC",msa,NC,2024,175.0

In [296]:
sales_count = sales_count.drop(columns=['Region_ID', 'Size_Rank', 'Region_Name', 'Region_Type'])
sales_count

      State_Name  Year  Sales_Count
0             NY  2018      14471.0
1             CA  2018       6835.0
2             IL  2018       7428.0
3             TX  2018       5278.0
4             TX  2018       4730.0
...          ...   ...          ...
25195         NJ  2024        244.0
25196         FL  2024         97.0
25197         UT  2024        175.0
25198         NC  2024        130.0
25199         NC  2024        175.0

[25200 rows x 3 columns]

In [297]:
sales_count = sales_count.groupby(['State_Name', 'Year']).agg({'Sales_Count': 'sum'}).reset_index()
sales_count.head()

  State_Name  Year  Sales_Count
0         AK  2018       5554.0
1         AK  2019       5462.0
2         AK  2020       5693.0
3         AK  2021       6700.0
4         AK  2022       5643.0

In [298]:
sales_count.shape

(343, 3)

In [299]:
sales_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   State_Name   343 non-null    str
 1   Year         343 non-null    int64
 2   Sales_Count  343 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 8.2 KB

In [300]:
sales_count['State_Name'].value_counts()

State_Name
AK    7
AL    7
AR    7
AZ    7
CA    7
CO    7
CT    7
DE    7
FL    7
GA    7
HI    7
IA    7
ID    7
IL    7
IN    7
KS    7
KY    7
LA    7
MA    7
MD    7
ME    7
MI    7
MN    7
MO    7
MS    7
MT    7
NC    7
ND    7
NE    7
NH    7
NJ    7
NM    7
NV    7
NY    7
OH    7
OK    7
OR    7
PA    7
RI    7
SC    7
SD    7
TN    7
TX    7
UT    7
VA    7
VT    7
WA    7
WI    7
WV    7
Name: count, dtype: int64

In [301]:
sales_count['State_Name'].value_counts().value_counts()

count
7    49
Name: count, dtype: int64

### The states count is inconsistent, with missing data for Wyoming (WY). Upon investigation, it appears Zillow didn't record sales data for Wyoming, resulting in incomplete data.

In [302]:
affordability_with_sales_count_2018_2024 = affordability_with_inventory_2018_2024.merge(sales_count, how= 'left', on= ['State_Name', 'Year'])

In [303]:
consumer_price_index

   Year  Average_CPI   CPI_Index
0  2018   251.099500  100.000000
1  2019   255.652583  101.813259
2  2020   258.855750  103.088915
3  2021   270.967917  107.912567
4  2022   292.625417  116.537634
5  2023   304.704167  121.347978
6  2024   313.697833  124.929693

In [304]:
affordability_with_cpi_2018_2024 = affordability_with_sales_count_2018_2024.merge(consumer_price_index, how= 'left', on= 'Year')

In [305]:
affordability_with_cpi_2018_2024

,State_Name,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Sales_Count,Average_CPI,CPI_Index
0,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111,5554.0,251.099500,100.000000
1,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949,5462.0,255.652583,101.813259
2,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889,5693.0,258.855750,103.088915
3,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358,1771.522222,6700.0,270.967917,107.912567
4,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436,1433.678788,5643.0,292.625417,116.537634
...,...,...,...,...,...,...,...,...,...,...,...
345,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697,NaN,258.855750,103.088915
346,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424,NaN,270.967917,107.912567
347,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,NaN,292.625417,116.537634
348,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,NaN,304.704167,121.347978
349,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,NaN,313.697833,124.929693

In [306]:
# Map state abbreviations to full names
state_map = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming'
}
   
affordability_with_cpi_2018_2024['State_Abbr'] = affordability_with_cpi_2018_2024['State_Name'].map(state_map)

In [307]:
affordability_with_cpi_2018_2024.info(memory_usage=True)

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State_Name         350 non-null    str
 1   Year               350 non-null    int64
 2   Median_Home_Value  350 non-null    float64
 3   Median_Income      350 non-null    float64
 4   Price_To_Income    350 non-null    float64
 5   Mortgage_Rate_pct  350 non-null    float64
 6   Median_Rent_Price  350 non-null    float64
 7   Active_Listings    350 non-null    float64
 8   Sales_Count        343 non-null    float64
 9   Average_CPI        350 non-null    float64
 10  CPI_Index          350 non-null    float64
 11  State_Abbr         350 non-null    str
dtypes: float64(9), int64(1), str(2)
memory usage: 32.9 KB

In [308]:
affordability_with_cpi_2018_2024

,State_Name,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Sales_Count,Average_CPI,CPI_Index,State_Abbr
0,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111,5554.0,251.099500,100.000000,Alaska
1,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949,5462.0,255.652583,101.813259,Alaska
2,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889,5693.0,258.855750,103.088915,Alaska
3,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358,1771.522222,6700.0,270.967917,107.912567,Alaska
4,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436,1433.678788,5643.0,292.625417,116.537634,Alaska
...,...,...,...,...,...,...,...,...,...,...,...,...
345,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697,NaN,258.855750,103.088915,Wyoming
346,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424,NaN,270.967917,107.912567,Wyoming
347,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,NaN,292.625417,116.537634,Wyoming
348,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,NaN,304.704167,121.347978,Wyoming
349,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,NaN,313.697833,124.929693,Wyoming

In [309]:
affordability_with_cpi_2018_2024 = affordability_with_cpi_2018_2024.rename(columns= {'State_Name': 'State_Abbr',
                                                                            'State_Abbr': 'State_Name'})

In [310]:
affordability_with_cpi_2018_2024 = affordability_with_cpi_2018_2024[['State_Name',
                                                                     'State_Abbr', 
                                                                     'Year', 
                                                                     'Median_Home_Value',
                                                                     'Median_Income', 
                                                                     'Price_To_Income', 
                                                                     'Mortgage_Rate_pct', 
                                                                     'Median_Rent_Price', 
                                                                     'Active_Listings', 
                                                                     'Average_CPI', 
                                                                     'CPI_Index',
                                                                     'Sales_Count']]

In [311]:
affordability_with_cpi_2018_2024.head()

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count
0,Alaska,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111,251.099500,100.000000,5554.0
1,Alaska,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949,255.652583,101.813259,5462.0
2,Alaska,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889,258.855750,103.088915,5693.0
3,Alaska,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358,1771.522222,270.967917,107.912567,6700.0
4,Alaska,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436,1433.678788,292.625417,116.537634,5643.0

In [312]:
household_estimate

        State_Name  Household_Estimate  Year
0        Wisconsin             2371960  2018
1          Wyoming              230252  2018
2      Mississippi             1108630  2018
3         Missouri             2434806  2018
4          Montana              431421  2018
..             ...                 ...   ...
345       Virginia             3449307  2024
346     Washington             3168080  2024
347  West Virginia              740840  2024
348      Wisconsin             2535198  2024
349        Wyoming              256289  2024

[350 rows x 3 columns]

In [313]:
affordability_with_hh_estimate_2018_2024 = affordability_with_cpi_2018_2024.merge(household_estimate,how= 'left', on= ['State_Name', 'Year'])

In [314]:
affordability_with_hh_estimate_2018_2024.head(3)

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate
0,Alaska,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111,251.099500,100.000000,5554.0,254551
1,Alaska,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949,255.652583,101.813259,5462.0,252199
2,Alaska,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889,258.855750,103.088915,5693.0,255173

In [315]:
pop_growth

        State_Name  Year  Population_Estimate
0          Alabama  2018              4891628
1           Alaska  2018               736624
2          Arizona  2018              7164228
3         Arkansas  2018              3012161
4       California  2018             39437463
..             ...   ...                  ...
345       Virginia  2024              8819642
346     Washington  2024              7927958
347  West Virginia  2024              1767402
348      Wisconsin  2024              5957168
349        Wyoming  2024               586722

[350 rows x 3 columns]

In [316]:
pop_growth[(pop_growth['Year']==2024)].groupby('State_Name')['Population_Estimate'].sum().sort_values()

State_Name
Wyoming             586722
Vermont             646521
Alaska              736537
North Dakota        793387
South Dakota        927110
Delaware           1050123
Rhode Island       1110415
Montana            1137557
Maine              1408438
New Hampshire      1408518
Hawaii             1434952
West Virginia      1767402
Idaho              2000872
Nebraska           2005591
New Mexico         2126774
Mississippi        2950172
Kansas             2965252
Arkansas           3096080
Iowa               3230454
Nevada             3253543
Utah               3502983
Connecticut        3674449
Oklahoma           4097758
Oregon             4265324
Kentucky           4584046
Louisiana          4614878
Alabama            5163055
South Carolina     5490316
Minnesota          5797405
Wisconsin          5957168
Colorado           5988502
Missouri           6243544
Maryland           6245314
Indiana            6934754
Massachusetts      7138560
Tennessee          7251291
Arizona            7556424
Washington         7927958
Virginia           8819642
New Jersey         9506354
Michigan          10099962
North Carolina    11052061
Georgia           11204208
Ohio              11860621
Illinois          12703033
Pennsylvania      13045848
New York          20001419
Florida           23265838
Texas             31318578
California        39364774
Name: Population_Estimate, dtype: int64

In [317]:
affordability_full_2018_2024 = affordability_with_hh_estimate_2018_2024.merge(pop_growth,how= 'left', on= ['State_Name', 'Year'])

In [318]:
affordability_full_2018_2024

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate
0,Alaska,AK,2018,292855.925684,84540.0,3.464111,4.539042,1184.985788,2969.711111,251.099500,100.000000,5554.0,254551,736624
1,Alaska,AK,2019,306141.400620,95010.0,3.222202,3.933750,1199.214250,2840.244949,255.652583,101.813259,5462.0,252199,733603
2,Alaska,AK,2020,317136.642502,89650.0,3.537497,3.113667,1225.571045,2329.938889,258.855750,103.088915,5693.0,255173,732906
3,Alaska,AK,2021,334507.770729,93150.0,3.591066,2.955708,1386.856358,1771.522222,270.967917,107.912567,6700.0,271311,734590
4,Alaska,AK,2022,356421.134816,95670.0,3.725527,5.327500,1500.786436,1433.678788,292.625417,116.537634,5643.0,274574,733659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Wyoming,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697,258.855750,103.088915,NaN,233231,577669
346,Wyoming,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424,270.967917,107.912567,NaN,242763,579662
347,Wyoming,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,292.625417,116.537634,NaN,243321,581742
348,Wyoming,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,304.704167,121.347978,NaN,247368,584666
349,Wyoming,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,313.697833,124.929693,NaN,256289,586722

In [319]:
affordability_full_2018_2024['State_Name'].isna().sum()

np.int64(0)

In [320]:
affordability_full_2018_2024.sample(3)

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate
161,Missouri,MO,2018,132661.312013,75920.0,1.747383,4.539042,826.566344,38380.655556,251.099500,100.000000,97377.0,2434806,6125986
177,Montana,MT,2020,295619.810719,68060.0,4.343518,3.113667,957.645943,3949.795455,258.855750,103.088915,2787.0,436048,1087156
214,New Jersey,NJ,2022,382190.480584,98430.0,3.882866,5.327500,1920.322123,3602.856061,292.625417,116.537634,19571.0,3516978,9298402

In [321]:
affordability_full_2018_2024.isna().sum()

State_Name             0
State_Abbr             0
Year                   0
Median_Home_Value      0
Median_Income          0
Price_To_Income        0
Mortgage_Rate_pct      0
Median_Rent_Price      0
Active_Listings        0
Average_CPI            0
CPI_Index              0
Sales_Count            7
Household_Estimate     0
Population_Estimate    0
dtype: int64

In [322]:
affordability_full_2018_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State_Name           350 non-null    str
 1   State_Abbr           350 non-null    str
 2   Year                 350 non-null    int64
 3   Median_Home_Value    350 non-null    float64
 4   Median_Income        350 non-null    float64
 5   Price_To_Income      350 non-null    float64
 6   Mortgage_Rate_pct    350 non-null    float64
 7   Median_Rent_Price    350 non-null    float64
 8   Active_Listings      350 non-null    float64
 9   Average_CPI          350 non-null    float64
 10  CPI_Index            350 non-null    float64
 11  Sales_Count          343 non-null    float64
 12  Household_Estimate   350 non-null    int64
 13  Population_Estimate  350 non-null    int64
dtypes: float64(9), int64(3), str(2)
memory usage: 38.4 KB

In [323]:
affordability_full_2018_2024.dtypes

State_Name                 str
State_Abbr                 str
Year                     int64
Median_Home_Value      float64
Median_Income          float64
Price_To_Income        float64
Mortgage_Rate_pct      float64
Median_Rent_Price      float64
Active_Listings        float64
Average_CPI            float64
CPI_Index              float64
Sales_Count            float64
Household_Estimate       int64
Population_Estimate      int64
dtype: object

In [324]:
affordability_full_2018_2024.describe()

,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate
count,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000,343.000000,3.500000e+02,3.500000e+02
mean,2021.000000,266947.084820,81889.685714,3.202618,4.769815,1282.455468,22101.861198,278.229024,110.804292,79854.868805,2.531383e+06,6.642286e+06
std,2.002863,129010.184633,13378.667777,1.247157,1.466801,343.333998,28063.640803,23.455072,9.340947,95580.270085,2.654391e+06,7.400280e+06
min,2018.000000,109396.801182,51820.000000,1.293062,2.955708,797.139267,728.866667,251.099500,100.000000,2064.000000,2.302520e+05,5.776690e+05
25%,2019.000000,170008.571705,72390.000000,2.307488,3.113667,1013.396924,5333.068939,255.652583,101.813259,14454.500000,7.374658e+05,1.910019e+06
50%,2021.000000,235128.404488,81240.000000,2.887435,4.539042,1210.744850,13246.612879,270.967917,107.912567,48135.000000,1.784803e+06,4.591412e+06
75%,2023.000000,330463.505825,91020.000000,3.844856,6.723667,1489.208639,26474.011301,304.704167,121.347978,111536.000000,3.012310e+06,7.739940e+06
max,2024.000000,865627.958794,115800.000000,8.811360,6.795375,2819.425551,171806.486580,313.697833,124.929693,602890.000000,1.379764e+07,3.952781e+07

-----------------------------------------------------------------------------------------------------------------------------------

### Create Growth Metrics (Within Each State)
Creating columns that calculate growth per state..
- Home Value Growth (YoY %)
- Income Growth (YoY %)

In [325]:

affordability_full_2018_2024 = affordability_full_2018_2024.sort_values(["State_Name", "Year"])

affordability_full_2018_2024 = affordability_full_2018_2024.assign(Home_Value_YoY_pct = (
    affordability_full_2018_2024.groupby("State_Name")["Median_Home_Value"]
      .pct_change() * 100),
                                                                   Income_YoY_pct = (
    affordability_full_2018_2024.groupby("State_Name")["Median_Income"]
      .pct_change() * 100)                   
                                                                  )

In [326]:
affordability_full_2018_2024

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct
7,Alabama,AL,2018,138391.021859,61420.0,2.253191,4.539042,945.009643,26620.333333,251.099500,100.000000,55471.0,1855184,4891628,NaN,NaN
8,Alabama,AL,2019,145333.040507,68110.0,2.133799,3.933750,986.246137,23632.729040,255.652583,101.813259,56900.0,1897576,4907965,5.016235,10.892218
9,Alabama,AL,2020,156389.809857,65600.0,2.383991,3.113667,1001.357374,19071.363636,258.855750,103.088915,61574.0,1888504,5032962,7.607884,-3.685215
10,Alabama,AL,2021,176436.486012,65360.0,2.699457,2.955708,1108.413589,14760.381818,270.967917,107.912567,72371.0,1967559,5050058,12.818403,-0.365854
11,Alabama,AL,2022,197708.554710,63870.0,3.095484,5.327500,1172.455744,14522.117677,292.625417,116.537634,62426.0,2016448,5076868,12.056502,-2.279682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Wyoming,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697,258.855750,103.088915,NaN,233231,577669,5.741126,-0.557385
346,Wyoming,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424,270.967917,107.912567,NaN,242763,579662,14.749416,3.923567
347,Wyoming,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,292.625417,116.537634,NaN,243321,581742,15.581758,-4.486394
348,Wyoming,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,304.704167,121.347978,NaN,247368,584666,4.175310,1.642710
349,Wyoming,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,313.697833,124.929693,NaN,256289,586722,3.749795,-0.656566

### Why This Matters

This allows for direct comparison:

Is home price growth > income growth?

***Note:*** That’s the first real affordability signal.

-----------------------------------------------------------------------------------------------------------------------------------

### Inflation Adjustment (Real Values)
Creating columns that convert nominal values to real values by adjusting for inflation
- Real_Home_Value
- Real_Income

In [327]:
affordability_full_2018_2024 = (affordability_full_2018_2024
                                .assign(Real_Home_Value = (affordability_full_2018_2024["Median_Home_Value"] / 
                                        affordability_full_2018_2024["CPI_Index"] * 100),
                                        Real_Income = (affordability_full_2018_2024["Median_Income"] / 
                                                       affordability_full_2018_2024["CPI_Index"] * 100)))

In [328]:
affordability_full_2018_2024.head(2)

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income
7,Alabama,AL,2018,138391.021859,61420.0,2.253191,4.539042,945.009643,26620.333333,251.099500,100.000000,55471.0,1855184,4891628,NaN,NaN,138391.021859,61420.000000
8,Alabama,AL,2019,145333.040507,68110.0,2.133799,3.933750,986.246137,23632.729040,255.652583,101.813259,56900.0,1897576,4907965,5.016235,10.892218,142744.709750,66896.984658

### Why This Matters

If home values rose 10% but inflation rose 8%, real growth is only 2%.

This prevents false crisis signals.

-----------------------------------------------------------------------------------------------------------------------------------

### Mortgage Burden (Critical Step)

compute true affordability pressure.

Estimated monthly mortgage payment using amortization formula.

In [329]:

r = affordability_full_2018_2024["Mortgage_Rate_pct"] / 100 / 12
n = 30 * 12

affordability_full_2018_2024["Monthly_Mortgage"] = (
    affordability_full_2018_2024["Median_Home_Value"] * 0.8 *
    (r * (1 + r)**n) / ((1 + r)**n - 1)
)

In [330]:
affordability_full_2018_2024["Mortgage_Burden_pct"] = (
    affordability_full_2018_2024["Monthly_Mortgage"] * 12 / affordability_full_2018_2024["Median_Income"]
) * 100

In [331]:
affordability_full_2018_2024[affordability_full_2018_2024['Mortgage_Burden_pct']>=30]

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income,Monthly_Mortgage,Mortgage_Burden_pct
32,California,CA,2022,593903.693955,90930.0,6.531438,5.327500,2142.473677,72014.293939,292.625417,116.537634,353688.0,13550586,39125347,12.442964,-2.914798,509623.949618,78026.296537,2646.499604,34.925762
33,California,CA,2023,580671.771655,92200.0,6.297958,6.795375,2155.121865,60728.446970,304.704167,121.347978,265683.0,13699816,39181667,-2.227958,1.396679,478517.878904,75979.840228,3027.005436,39.397034
34,California,CA,2024,601193.344989,100600.0,5.976077,6.723667,2210.324181,69694.356061,313.697833,124.929693,274902.0,13797638,39364774,3.534109,9.110629,481225.345824,80525.292227,3111.048728,37.109925
39,Colorado,CO,2022,561764.505649,95870.0,5.859649,5.327500,1750.606189,18886.462121,292.625417,116.537634,84113.0,2384584,5853355,18.729966,-1.712118,482045.572436,82265.270526,2503.283877,31.333479
40,Colorado,CO,2023,563471.895329,99140.0,5.683598,6.795375,1892.805322,19502.671212,304.704167,121.347978,65537.0,2428261,5912240,0.303933,3.410869,464343.867460,81698.930154,2937.343562,35.553886
41,Colorado,CO,2024,581541.986947,106500.0,5.460488,6.723667,2075.464628,22840.340909,313.697833,124.929693,67145.0,2479892,5988502,3.206920,7.423845,465495.411938,85247.948530,3009.357096,33.908249
61,Florida,FL,2023,361665.133747,74070.0,4.882748,6.795375,1881.377227,120893.283983,304.704167,121.347978,369833.0,8966402,22929248,3.771951,6.300230,298039.686312,61039.335853,1885.337602,30.544149
62,Florida,FL,2024,365996.510845,75630.0,4.839303,6.723667,1907.708477,164640.371212,313.697833,124.929693,337529.0,9141675,23265838,1.197621,2.106116,292961.987969,60538.050210,1893.954731,30.050849
74,Hawaii,HI,2022,818196.301529,97010.0,8.434144,5.327500,2515.367817,4310.772727,292.625417,116.537634,17488.0,494827,1437812,19.586353,2.797499,702087.619579,83243.495293,3645.971914,45.100158
75,Hawaii,HI,2023,838990.162739,99880.0,8.399982,6.795375,2654.201456,4483.771212,304.704167,121.347978,12493.0,493898,1434950,2.541427,2.958458,691391.957890,82308.746659,4373.602967,52.546291
76,Hawaii,HI,2024,865627.958794,98240.0,8.811360,6.723667,2819.425551,5752.606061,313.697833,124.929693,12245.0,493151,1434952,3.174983,-1.641970,692892.090868,78636.229705,4479.442068,54.716312
88,Idaho,ID,2022,448523.424216,77370.0,5.797123,5.327500,1389.845786,6085.554545,292.625417,116.537634,13331.0,717151,1942951,18.170387,-12.388178,384874.317624,66390.570362,1998.669273,30.999136
89,Idaho,ID,2023,434195.242601,75820.0,5.726658,6.795375,1409.775116,6038.818182,304.704167,121.347978,10731.0,733244,1970497,-3.194522,-2.003360,357810.034278,62481.469480,2263.432499,35.823252
90,Idaho,ID,2024,443536.384539,81650.0,5.432166,6.723667,1357.441015,6450.519697,313.697833,124.929693,11236.0,751181,2000872,2.151369,7.689264,355028.796999,65356.760540,2295.207219,33.732378
130,Massachusetts,MA,2022,605397.581223,99720.0,6.070975,5.327500,1868.453788,14113.613636,292.625417,116.537634,85131.0,2797776,7025465,16.251916,0.332025,519486.761191,85568.924344,2697.717618,32.463509
131,Massachusetts,MA,2023,629953.667738,109300.0,5.763529,6.795375,2013.427078,11679.181818,304.704167,121.347978,65223.0,2800984,7073479,4.056192,9.606899,519129.924355,90071.545953,3283.908861,36.053894
132,Massachusetts,MA,2024,669472.173424,113900.0,5.877719,6.723667,2120.977039,12858.234848,313.697833,124.929693,68730.0,2829804,7138560,6.273240,4.208600,535879.149130,91171.280165,3464.377261,36.499146
179,Montana,MT,2022,440585.896482,77790.0,5.663786,5.327500,1573.211467,2824.416667,292.625417,116.537634,2539.0,464072,1121533,20.160651,4.234222,378063.189363,66750.968961,1963.298784,30.286136
180,Montana,MT,2023,443227.710140,81270.0,5.453768,6.795375,1509.864695,3220.928788,304.704167,121.347978,2111.0,472867,1130612,0.599614,4.473583,365253.477233,66972.685632,2310.518185,34.116178
181,Montana,MT,2024,463633.865229,81920.0,5.659593,6.723667,1560.380045,3676.166667,313.697833,124.929693,2064.0,468981,1137557,4.603989,0.799803,371115.829858,65572.882099,2399.207441,35.144640
229,Nevada,NV,2023,412717.210320,83410.0,4.948054,6.795375,1714.582085,11523.229798,304.704167,121.347978,35302.0,1224685,3211077,-3.878721,8.184176,340110.495654,68736.209039,2151.468868,30.952675
230,Nevada,NV,2024,426392.988437,80590.0,5.290892,6.723667,1731.300601,11840.264394,313.697833,124.929693,36947.0,1238925,3253543,3.313595,-3.380890,341306.361801,64508.283306,2206.493760,32.855100
271,Rhode Island,RI,2023,438277.172385,83980.0,5.218828,6.795375,1824.539605,2351.416667,304.704167,121.347978,13036.0,443980,1101183,4.772548,-2.326122,361173.856108,69205.932563,2284.711343,32.646506
272,Rhode Island,RI,2024,472478.517623,92290.0,5.119499,6.723667,1940.973029,2578.750000,313.697833,124.929693,13299.0,448318,1110415,7.803588,9.895213,378195.533820,73873.550891,2444.976651,31.790790
307,Utah,UT,2024,502898.705267,104000.0,4.835564,6.723667,1775.668479,10827.242424,313.697833,124.929693,35441.0,1184428,3502983,2.159706,0.192678,402545.379742,83246.822978,2602.394705,30.027631
348,Wyoming,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,304.704167,121.347978,NaN,247368,584666,4.175310,1.642710,347597.388084,65266.847571,2198.829405,33.315597
349,Wyoming,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,313.697833,124.929693,NaN,256289,586722,3.749795,-0.656566,350292.327613,62979.423384,2264.586664,34.538688

### What it means 
If Mortgage_Burden_pct = 35%

It means:

35% of annual income is required to service the mortgage.

Above 30% is generally considered financially stressed.

- Below 20% → very affordable states/years
- 30%+ → affordability stress
- 50%+ → severe pressure

-----------------------------------------------------------------------------------------------------------------------------------

### Rent Burden %

Calculate rental pressure.

In [332]:
affordability_full_2018_2024["Rent_Burden_pct"] = (
    affordability_full_2018_2024["Median_Rent_Price"] * 12 / affordability_full_2018_2024["Median_Income"]
) * 100

In [333]:
affordability_full_2018_2024.head(3)

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income,Monthly_Mortgage,Mortgage_Burden_pct,Rent_Burden_pct
7,Alabama,AL,2018,138391.021859,61420.0,2.253191,4.539042,945.009643,26620.333333,251.099500,100.000000,55471.0,1855184,4891628,NaN,NaN,138391.021859,61420.000000,563.536784,11.010162,18.463230
8,Alabama,AL,2019,145333.040507,68110.0,2.133799,3.933750,986.246137,23632.729040,255.652583,101.813259,56900.0,1897576,4907965,5.016235,10.892218,142744.709750,66896.984658,550.642252,9.701523,17.376235
9,Alabama,AL,2020,156389.809857,65600.0,2.383991,3.113667,1001.357374,19071.363636,258.855750,103.088915,61574.0,1888504,5032962,7.607884,-3.685215,151703.808242,63634.387878,535.177256,9.789828,18.317513

### Now we can compare:

Buying burden vs Renting burden

Which is worse?

Is renting becoming equally unaffordable?

-----------------------------------------------------------------------------------------------------------------------------------

### Affordability Gap and Housing Cost
This metric measures the divergence between housing costs and affordability, indicating how accessible houses are to potential buyers.

In [334]:
affordability_full_2018_2024['Annual_Housing_Cost'] = (
    affordability_full_2018_2024['Monthly_Mortgage'] * 12 +
    (affordability_full_2018_2024['Median_Home_Value'] * 0.012) +   # property tax
    (affordability_full_2018_2024['Median_Home_Value'] * 0.01)      # maintenance
)

In [335]:
affordability_full_2018_2024['Affordability_pct'] = (
    affordability_full_2018_2024['Annual_Housing_Cost'] / affordability_full_2018_2024['Median_Income']
) * 100

In [336]:
# Required_Income = Annual Housing Cost / Affordability Threshold(30%)
affordability_full_2018_2024['Required_Income'] = affordability_full_2018_2024['Annual_Housing_Cost'] / 0.3

In [337]:
affordability_full_2018_2024["Affordability_Gap_pct"] = (
    (affordability_full_2018_2024["Required_Income"] - affordability_full_2018_2024["Median_Income"])
    / 
    affordability_full_2018_2024["Required_Income"] * 100
)

In [338]:
affordability_full_2018_2024.head(2)

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Sales_Count,Household_Estimate,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income,Monthly_Mortgage,Mortgage_Burden_pct,Rent_Burden_pct,Annual_Housing_Cost,Affordability_pct,Required_Income,Affordability_Gap_pct
7,Alabama,AL,2018,138391.021859,61420.0,2.253191,4.539042,945.009643,26620.333333,251.099500,100.000000,55471.0,1855184,4891628,NaN,NaN,138391.021859,61420.000000,563.536784,11.010162,18.463230,9807.043890,15.967183,32690.146300,-87.885363
8,Alabama,AL,2019,145333.040507,68110.0,2.133799,3.933750,986.246137,23632.729040,255.652583,101.813259,56900.0,1897576,4907965,5.016235,10.892218,142744.709750,66896.984658,550.642252,9.701523,17.376235,9805.033918,14.395880,32683.446394,-108.392956

### It Means..
If positive → housing is outpacing income.

If negative → income catching up.

In [339]:
affordability_full_2018_2024.shape

(350, 25)

In [340]:
affordability_full_2018_2024.columns

Index(['State_Name', 'State_Abbr', 'Year', 'Median_Home_Value',
       'Median_Income', 'Price_To_Income', 'Mortgage_Rate_pct',
       'Median_Rent_Price', 'Active_Listings', 'Average_CPI', 'CPI_Index',
       'Sales_Count', 'Household_Estimate', 'Population_Estimate',
       'Home_Value_YoY_pct', 'Income_YoY_pct', 'Real_Home_Value',
       'Real_Income', 'Monthly_Mortgage', 'Mortgage_Burden_pct',
       'Rent_Burden_pct', 'Annual_Housing_Cost', 'Affordability_pct',
       'Required_Income', 'Affordability_Gap_pct'],
      dtype='str')

In [341]:
affordability_full_2018_2024 = (affordability_full_2018_2024[
      ['State_Name', 'State_Abbr', 'Year', 'Median_Home_Value',
       'Median_Income', 'Price_To_Income', 'Mortgage_Rate_pct',
       'Median_Rent_Price', 'Active_Listings', 'Average_CPI', 'CPI_Index',
       'Population_Estimate', 'Home_Value_YoY_pct',
       'Income_YoY_pct', 'Real_Home_Value', 'Real_Income', 'Monthly_Mortgage',
       'Mortgage_Burden_pct', 'Rent_Burden_pct', 'Annual_Housing_Cost',
       'Affordability_pct', 'Affordability_Gap_pct', 'Household_Estimate', 'Required_Income', 'Sales_Count']])

In [342]:
# save affordability_full_2018_2024 dataframe as us_housing_affordability_report.csv 
affordability_full_2018_2024.to_csv('us_housing_affordability_report.csv', index = False)

In [343]:
affordability_full_2018_2024[affordability_full_2018_2024['Affordability_pct']>= 30]

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income,Monthly_Mortgage,Mortgage_Burden_pct,Rent_Burden_pct,Annual_Housing_Cost,Affordability_pct,Affordability_Gap_pct,Household_Estimate,Required_Income,Sales_Count
5,Alaska,AK,2023,358097.619293,100700.0,3.556084,6.795375,1591.364608,1244.916667,304.704167,121.347978,734654,0.470366,5.257657,295099.781993,82984.489272,1866.740374,22.245168,18.963630,30279.032110,30.068552,0.227987,276852,100930.107035,4116.0
6,Alaska,AK,2024,363466.526295,91260.0,3.982758,6.723667,1654.113980,1355.909091,313.697833,124.929693,736537,1.499286,-9.374379,290936.861277,73049.087163,1880.862594,24.731921,21.750348,30566.614709,33.493989,10.431691,274045,101888.715697,4203.0
25,Arizona,AZ,2022,350000.354871,78300.0,4.469992,5.327500,1514.944284,28409.021212,292.625417,116.537634,7370065,18.085682,-3.701882,300332.469780,67188.595830,1559.639736,23.902525,23.217537,26415.684639,33.736507,11.075559,2850377,88052.282129,123150.0
26,Arizona,AZ,2023,347264.573441,84800.0,4.095101,6.795375,1561.699621,26095.328788,304.704167,121.347978,7452073,-0.781651,8.301405,286172.525019,69881.675177,1810.268387,25.617005,22.099523,29363.041259,34.626228,13.360473,2907014,97876.804197,89582.0
27,Arizona,AZ,2024,358126.174166,84700.0,4.228172,6.723667,1595.242870,28480.898990,313.697833,124.929693,7556424,3.127760,-0.117925,286662.175235,67798.133714,1853.227399,26.255878,22.600843,30117.504615,35.557857,15.630460,2982475,100391.682049,88632.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,Washington,WA,2023,440765.281078,95850.0,4.598490,6.795375,1601.361112,14620.995455,304.704167,121.347978,7838655,-1.339053,0.545474,363224.247659,78987.718935,2297.681697,28.765968,20.048339,37269.016547,38.882646,22.844758,3101265,124230.055158,59991.0
328,Washington,WA,2024,452278.359487,97500.0,4.638752,6.723667,1668.506180,16400.963636,313.697833,124.929693,7927958,2.612066,1.721440,362026.312778,78043.896542,2340.445095,28.805478,20.535461,38035.465044,39.010733,23.098088,3168080,126784.883481,63625.0
347,Wyoming,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,292.625417,116.537634,581742,15.581758,-4.486394,347438.586253,66862.520908,1804.263872,27.786405,16.818362,30558.894057,39.218293,23.505085,243321,101862.980189,NaN
348,Wyoming,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,304.704167,121.347978,584666,4.175310,1.642710,347597.388084,65266.847571,2198.829405,33.315597,17.788849,35665.605729,45.032330,33.381196,247368,118885.352430,NaN
349,Wyoming,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,313.697833,124.929693,586722,3.749795,-0.656566,350292.327613,62979.423384,2264.586664,34.538688,24.875249,36802.660779,46.775115,35.863333,256289,122675.535930,NaN

In [344]:
pd.set_option('display.max_columns', None)
affordability_full_2018_2024

,State_Name,State_Abbr,Year,Median_Home_Value,Median_Income,Price_To_Income,Mortgage_Rate_pct,Median_Rent_Price,Active_Listings,Average_CPI,CPI_Index,Population_Estimate,Home_Value_YoY_pct,Income_YoY_pct,Real_Home_Value,Real_Income,Monthly_Mortgage,Mortgage_Burden_pct,Rent_Burden_pct,Annual_Housing_Cost,Affordability_pct,Affordability_Gap_pct,Household_Estimate,Required_Income,Sales_Count
7,Alabama,AL,2018,138391.021859,61420.0,2.253191,4.539042,945.009643,26620.333333,251.099500,100.000000,4891628,NaN,NaN,138391.021859,61420.000000,563.536784,11.010162,18.463230,9807.043890,15.967183,-87.885363,1855184,32690.146300,55471.0
8,Alabama,AL,2019,145333.040507,68110.0,2.133799,3.933750,986.246137,23632.729040,255.652583,101.813259,4907965,5.016235,10.892218,142744.709750,66896.984658,550.642252,9.701523,17.376235,9805.033918,14.395880,-108.392956,1897576,32683.446394,56900.0
9,Alabama,AL,2020,156389.809857,65600.0,2.383991,3.113667,1001.357374,19071.363636,258.855750,103.088915,5032962,7.607884,-3.685215,151703.808242,63634.387878,535.177256,9.789828,18.317513,9862.702885,15.034608,-99.539621,1888504,32875.676283,61574.0
10,Alabama,AL,2021,176436.486012,65360.0,2.699457,2.955708,1108.413589,14760.381818,270.967917,107.912567,5050058,12.818403,-0.365854,163499.479807,60567.551767,591.724270,10.863971,20.350311,10982.293933,16.802775,-78.541934,1967559,36607.646444,72371.0
11,Alabama,AL,2022,197708.554710,63870.0,3.095484,5.327500,1172.455744,14522.117677,292.625417,116.537634,5076868,12.056502,-2.279682,169652.109509,54806.329702,881.010873,16.552576,22.028290,14921.718675,23.362641,-28.410141,2016448,49739.062250,62426.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Wyoming,WY,2020,305284.297336,78500.0,3.888972,3.113667,968.464261,2357.069697,258.855750,103.088915,577669,5.741126,-0.557385,296136.880942,76147.857446,1044.704975,15.970012,14.804549,19252.714246,24.525751,-22.320415,233231,64175.714152,NaN
346,Wyoming,WY,2021,350311.948170,81580.0,4.294091,2.955708,1001.732737,1803.892424,270.967917,107.912567,579662,14.749416,3.923567,324625.719943,75598.238574,1174.859501,17.281581,14.734975,21805.176866,26.728582,-12.239401,242763,72683.922886,NaN
347,Wyoming,WY,2022,404896.708549,77920.0,5.196313,5.327500,1092.072283,1760.998485,292.625417,116.537634,581742,15.581758,-4.486394,347438.586253,66862.520908,1804.263872,27.786405,16.818362,30558.894057,39.218293,23.505085,243321,101862.980189,NaN
348,Wyoming,WY,2023,421802.402918,79200.0,5.325788,6.795375,1174.064030,1841.687879,304.704167,121.347978,584666,4.175310,1.642710,347597.388084,65266.847571,2198.829405,33.315597,17.788849,35665.605729,45.032330,33.381196,247368,118885.352430,NaN
349,Wyoming,WY,2024,437619.127898,78680.0,5.562012,6.723667,1630.987177,1889.562121,313.697833,124.929693,586722,3.749795,-0.656566,350292.327613,62979.423384,2264.586664,34.538688,24.875249,36802.660779,46.775115,35.863333,256289,122675.535930,NaN